/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorSelector: typeof import('./src/components/common/ColorSelector.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    CurrencySelector: typeof import('./src/components/common/money/CurrencySelector.vue')['default']
    Descriptions: typeof import('./src/components/common/Descriptions.vue')['default']
    FloatingErrorTip: typeof import('./src/components/common/FloatingErrorTip.vue')['default']
    FormInput: typeof import('./src/components/common/FormInput.vue')['default']
    GenericItem: typeof import('./src/components/common/GenericItem.vue')['default']
    GenericViewItem: typeof import('./src/components/common/GenericViewItem.vue')['default']
    InputCommon: typeof import('./src/components/common/InputCommon.vue')['default']
    InputError: typeof import('./src/components/common/InputError.vue')['default']
    MobileBottomNav: typeof import('./src/components/common/MobileBottomNav.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PopupWrapper: typeof import('./src/components/common/PopupWrapper.vue')['default']
    PriorityBadge: typeof import('./src/components/common/PriorityBadge.vue')['default']
    PrioritySelector: typeof import('./src/components/common/PrioritySelector.vue')['default']
    ReminderSelector: typeof import('./src/components/common/ReminderSelector.vue')['default']
    RepeatPeriodSelector: typeof import('./src/components/common/RepeatPeriodSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
    SimplePagination: typeof import('./src/components/common/SimplePagination.vue')['default']
    WarningDialog: typeof import('./src/components/common/WarningDialog.vue')['default']
  }
}
