[package]
name = "money"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
validator = { workspace = true }
entity = { workspace = true }
common = { workspace = true }
