//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bil_reminder")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub name: String,
    pub enabled: i32,
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub category: String,
    pub amount: String,
    pub currency: String,
    pub due_at: String,
    pub bill_date: String,
    pub remind_date: String,
    pub repeat_period: String,
    pub is_paid: i32,
    pub priority: String,
    pub advance_value: Option<i32>,
    pub advance_unit: Option<String>,
    pub related_transaction_serial_num: Option<String>,
    pub color: Option<String>,
    pub is_deleted: i32,
    pub created_at: String,
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::RelatedTransactionSerialNum",
        to = "super::transactions::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Transactions,
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}