//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "bil_reminder")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub name: String,
    pub enabled: bool,
    pub r#type: String,
    pub description: Option<String>,
    pub category: String,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))", nullable)]
    pub amount: Option<Decimal>,
    pub currency: Option<String>,
    pub due_at: DateTimeWithTimeZone,
    pub bill_date: Option<DateTimeWithTimeZone>,
    pub remind_date: DateTimeWithTimeZone,
    pub repeat_period_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub repeat_period: Json,
    pub is_paid: bool,
    pub priority: String,
    pub advance_value: Option<i32>,
    pub advance_unit: Option<String>,
    pub related_transaction_serial_num: Option<String>,
    pub color: Option<String>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    // 新增高级提醒功能字段
    pub last_reminder_sent_at: Option<DateTimeWithTimeZone>,
    pub reminder_frequency: Option<String>,
    pub snooze_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub reminder_methods: Option<Json>,
    pub escalation_enabled: bool,
    pub escalation_after_hours: Option<i32>,
    pub timezone: Option<String>,
    pub smart_reminder_enabled: bool,
    pub auto_reschedule: bool,
    pub payment_reminder_enabled: bool,
    pub batch_reminder_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::transactions::Entity",
        from = "Column::RelatedTransactionSerialNum",
        to = "super::transactions::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Transactions,
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
