//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    pub icon: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_categories::Entity")]
    SubCategories,
}

impl Related<super::sub_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
