//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "family_ledger")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub name: Option<String>,
    pub description: String,
    pub base_currency: String,
    pub members: Option<String>,
    pub accounts: Option<String>,
    pub transactions: Option<String>,
    pub budgets: Option<String>,
    pub audit_logs: String,
    // 新增字段
    pub ledger_type: String,
    pub settlement_cycle: String,
    pub auto_settlement: bool,
    pub default_split_rule: Option<Json>,
    pub last_settlement_at: Option<DateTimeWithTimeZone>,
    pub next_settlement_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::BaseCurrency",
        to = "super::currency::Column::Code",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Currency,
    #[sea_orm(has_many = "super::family_ledger_account::Entity")]
    FamilyLedgerAccount,
    #[sea_orm(has_many = "super::family_ledger_member::Entity")]
    FamilyLedgerMember,
    #[sea_orm(has_many = "super::family_ledger_transaction::Entity")]
    FamilyLedgerTransaction,
    #[sea_orm(has_many = "super::split_rules::Entity")]
    SplitRules,
    #[sea_orm(has_many = "super::split_records::Entity")]
    SplitRecords,
    #[sea_orm(has_many = "super::debt_relations::Entity")]
    DebtRelations,
    #[sea_orm(has_many = "super::settlement_records::Entity")]
    SettlementRecords,
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl Related<super::family_ledger_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerAccount.def()
    }
}

impl Related<super::family_ledger_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerMember.def()
    }
}

impl Related<super::family_ledger_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerTransaction.def()
    }
}

impl Related<super::family_member::Entity> for Entity {
    fn to() -> RelationDef {
        super::family_ledger_member::Relation::FamilyMember.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::family_ledger_member::Relation::FamilyLedger
                .def()
                .rev(),
        )
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::family_ledger_transaction::Relation::Transactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::family_ledger_transaction::Relation::FamilyLedger
                .def()
                .rev(),
        )
    }
}

impl Related<super::split_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SplitRules.def()
    }
}

impl Related<super::split_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SplitRecords.def()
    }
}

impl Related<super::debt_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DebtRelations.def()
    }
}

impl Related<super::settlement_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
