//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "family_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub name: String,
    pub role: String,
    pub is_primary: i32,
    pub permissions: String,
    pub created_at: String,
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account::Entity")]
    Account,
    #[sea_orm(has_many = "super::family_ledger_member::Entity")]
    FamilyLedgerMember,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::family_ledger_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerMember.def()
    }
}

impl Related<super::family_ledger::Entity> for Entity {
    fn to() -> RelationDef {
        super::family_ledger_member::Relation::FamilyLedger.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::family_ledger_member::Relation::FamilyMember
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
