//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "family_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub name: String,
    pub role: String,
    pub is_primary: bool,
    pub permissions: String,
    // 新增字段
    pub user_id: Option<String>,
    pub avatar_url: Option<String>,
    pub color: Option<String>,
    pub total_paid: Decimal,
    pub total_owed: Decimal,
    pub balance: Decimal,
    pub status: String,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account::Entity")]
    Account,
    #[sea_orm(has_many = "super::family_ledger_member::Entity")]
    FamilyLedgerMember,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
    #[sea_orm(has_many = "super::split_records::Entity")]
    PayerSplitRecords,
    #[sea_orm(has_many = "super::split_records::Entity")]
    OweSplitRecords,
    #[sea_orm(has_many = "super::debt_relations::Entity")]
    CreditorDebtRelations,
    #[sea_orm(has_many = "super::debt_relations::Entity")]
    DebtorDebtRelations,
    #[sea_orm(has_many = "super::settlement_records::Entity")]
    InitiatedSettlementRecords,
    #[sea_orm(has_many = "super::settlement_records::Entity")]
    CompletedSettlementRecords,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::family_ledger_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerMember.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::family_ledger::Entity> for Entity {
    fn to() -> RelationDef {
        super::family_ledger_member::Relation::FamilyLedger.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::family_ledger_member::Relation::FamilyMember
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
