//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "notification_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub reminder_serial_num: String,
    pub notification_type: String,
    pub status: String,
    pub sent_at: Option<DateTimeWithTimeZone>,
    pub error_message: Option<String>,
    pub retry_count: i32,
    pub last_retry_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::reminder::Entity",
        from = "Column::ReminderSerialNum",
        to = "super::reminder::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Reminder,
}

impl Related<super::reminder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reminder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

