//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "operation_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub recorded_at: DateTimeWithTimeZone,
    pub operation: String,
    pub target_table: String,
    pub record_id: String,
    pub actor_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub changes_json: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub snapshot_json: Option<Json>,
    pub device_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
