//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "period_pms_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub period_serial_num: String,
    pub start_date: DateTimeWithTimeZone,
    pub end_date: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::period_pms_symptoms::Entity")]
    PeriodPmsSymptoms,
    #[sea_orm(
        belongs_to = "super::period_records::Entity",
        from = "Column::PeriodSerialNum",
        to = "super::period_records::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PeriodRecords,
}

impl Related<super::period_pms_symptoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodPmsSymptoms.def()
    }
}

impl Related<super::period_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
