//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "period_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub notes: Option<String>,
    pub start_date: DateTimeWithTimeZone,
    pub end_date: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::period_daily_records::Entity")]
    PeriodDailyRecords,
    #[sea_orm(has_many = "super::period_pms_records::Entity")]
    PeriodPmsRecords,
}

impl Related<super::period_daily_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodDailyRecords.def()
    }
}

impl Related<super::period_pms_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodPmsRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
