//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "task_dependency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_serial_num: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub depends_on_task_serial_num: String,
    pub created_at: String,
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::todo::Entity",
        from = "Column::DependsOnTaskSerialNum",
        to = "super::todo::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Todo2,
    #[sea_orm(
        belongs_to = "super::todo::Entity",
        from = "Column::TaskSerialNum",
        to = "super::todo::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Todo1,
}

impl ActiveModelBehavior for ActiveModel {}
