//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::localize::LocalizeModel;
use localize_model_derive::LocalizeModel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, LocalizeModel)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub transaction_type: String,
    pub transaction_status: String,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub refund_amount: Decimal,
    pub currency: String,
    pub description: String,
    pub notes: Option<String>,
    pub account_serial_num: String,
    pub to_account_serial_num: Option<String>,
    pub category: String,
    pub sub_category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub split_members: Option<Json>,
    pub payment_method: String,
    pub actual_payer_account: String,
    pub related_transaction_serial_num: Option<String>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    // 分期相关字段
    pub is_installment: Option<bool>,
    pub total_periods: Option<i32>,
    pub remaining_periods: Option<i32>,
    pub installment_plan_serial_num: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountSerialNum",
        to = "super::account::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Account,
    #[sea_orm(has_many = "super::bil_reminder::Entity")]
    BilReminder,
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::Currency",
        to = "super::currency::Column::Code",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Currency,
    #[sea_orm(has_many = "super::family_ledger_transaction::Entity")]
    FamilyLedgerTransaction,
    #[sea_orm(has_one = "super::installment_plans::Entity")]
    InstallmentPlan,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::bil_reminder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BilReminder.def()
    }
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl Related<super::family_ledger_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyLedgerTransaction.def()
    }
}

impl Related<super::installment_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstallmentPlan.def()
    }
}

impl Related<super::family_ledger::Entity> for Entity {
    fn to() -> RelationDef {
        super::family_ledger_transaction::Relation::FamilyLedger.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::family_ledger_transaction::Relation::Transactions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
