[package]
name = "migration"
version = "0.1.0"
edition = "2024"
description = "About Migration"


[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tauri-plugin-sql = { workspace = true }


[dependencies.sea-orm-migration]
version = "1.1.14"
features = [
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  # "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
  # "sqlx-postgres",         # `DATABASE_DRIVER` feature
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
]
