class CurrencySeed {
  const CurrencySeed({
    required this.code,
    required this.locale,
    required this.symbol,
    this.isDefault = false,
  });

  final String code;
  final String locale;
  final String symbol;
  final bool isDefault;
}

class MoneyCategorySeed {
  const MoneyCategorySeed({
    required this.id,
    required this.name,
    required this.kind,
    required this.icon,
    required this.color,
    required this.subCategories,
  });

  final String id;
  final String name;
  final String kind;
  final String icon;
  final String color;
  final List<MoneySubCategorySeed> subCategories;
}

class MoneySubCategorySeed {
  const MoneySubCategorySeed({
    required this.id,
    required this.name,
    required this.kind,
    required this.icon,
    required this.color,
  });

  final String id;
  final String name;
  final String kind;
  final String icon;
  final String color;
}

const defaultCurrencySeeds = <CurrencySeed>[
  CurrencySeed(code: 'CNY', locale: 'zh-CN', symbol: '¥', isDefault: true),
  CurrencySeed(code: 'USD', locale: 'en-US', symbol: r'$'),
  CurrencySeed(code: 'EUR', locale: 'de-DE', symbol: '€'),
  CurrencySeed(code: 'JPY', locale: 'ja-JP', symbol: '¥'),
  CurrencySeed(code: 'HKD', locale: 'zh-HK', symbol: r'HK$'),
  CurrencySeed(code: 'GBP', locale: 'en-GB', symbol: '£'),
  CurrencySeed(code: 'AUD', locale: 'en-AU', symbol: r'A$'),
  CurrencySeed(code: 'CAD', locale: 'en-CA', symbol: r'C$'),
  CurrencySeed(code: 'SGD', locale: 'en-SG', symbol: r'S$'),
  CurrencySeed(code: 'KRW', locale: 'ko-KR', symbol: '₩'),
];

const defaultMoneyCategorySeeds = <MoneyCategorySeed>[
  MoneyCategorySeed(
    id: 'expense_food',
    name: '餐饮',
    kind: 'expense',
    icon: 'restaurant',
    color: '#F97316',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_food_breakfast',
        name: '早餐',
        kind: 'expense',
        icon: 'breakfast_dining',
        color: '#FDBA74',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_lunch',
        name: '午餐',
        kind: 'expense',
        icon: 'lunch_dining',
        color: '#FB923C',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_dinner',
        name: '晚餐',
        kind: 'expense',
        icon: 'dinner_dining',
        color: '#F97316',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_restaurant',
        name: '餐厅堂食',
        kind: 'expense',
        icon: 'restaurant',
        color: '#FB923C',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_takeout',
        name: '外卖',
        kind: 'expense',
        icon: 'delivery_dining',
        color: '#F97316',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_groceries',
        name: '生鲜杂货',
        kind: 'expense',
        icon: 'local_grocery_store',
        color: '#EA580C',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_ingredients',
        name: '烹饪原料',
        kind: 'expense',
        icon: 'kitchen',
        color: '#C2410C',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_coffee_tea',
        name: '咖啡茶饮',
        kind: 'expense',
        icon: 'local_cafe',
        color: '#9A3412',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_drinks',
        name: '酒水饮料',
        kind: 'expense',
        icon: 'local_cafe',
        color: '#EA580C',
      ),
      MoneySubCategorySeed(
        id: 'expense_food_snacks',
        name: '零食',
        kind: 'expense',
        icon: 'bakery_dining',
        color: '#C2410C',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_transport',
    name: '交通',
    kind: 'expense',
    icon: 'directions_bus',
    color: '#0EA5E9',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_transport_public',
        name: '公交地铁',
        kind: 'expense',
        icon: 'subway',
        color: '#7DD3FC',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_taxi',
        name: '打车网约车',
        kind: 'expense',
        icon: 'local_taxi',
        color: '#38BDF8',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_train',
        name: '火车高铁',
        kind: 'expense',
        icon: 'train',
        color: '#0EA5E9',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_flight',
        name: '飞机',
        kind: 'expense',
        icon: 'flight',
        color: '#0284C7',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_fuel',
        name: '加油',
        kind: 'expense',
        icon: 'local_gas_station',
        color: '#0EA5E9',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_parking',
        name: '停车',
        kind: 'expense',
        icon: 'local_parking',
        color: '#0284C7',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_toll',
        name: '过路过桥',
        kind: 'expense',
        icon: 'toll',
        color: '#0369A1',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_bike',
        name: '共享单车',
        kind: 'expense',
        icon: 'pedal_bike',
        color: '#075985',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_parking_fine',
        name: '停车罚款',
        kind: 'expense',
        icon: 'gpp_bad',
        color: '#0C4A6E',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_ferry',
        name: '轮渡',
        kind: 'expense',
        icon: 'directions_boat',
        color: '#0369A1',
      ),
      MoneySubCategorySeed(
        id: 'expense_transport_maintenance',
        name: '保养维修',
        kind: 'expense',
        icon: 'build',
        color: '#0369A1',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_shopping',
    name: '购物',
    kind: 'expense',
    icon: 'shopping_bag',
    color: '#EC4899',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_shopping_daily',
        name: '日用品',
        kind: 'expense',
        icon: 'inventory_2',
        color: '#F9A8D4',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_clothing',
        name: '服饰',
        kind: 'expense',
        icon: 'checkroom',
        color: '#F472B6',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_footwear',
        name: '鞋包',
        kind: 'expense',
        icon: 'shopping_bag',
        color: '#EC4899',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_supermarket',
        name: '超市',
        kind: 'expense',
        icon: 'storefront',
        color: '#DB2777',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_online',
        name: '网购',
        kind: 'expense',
        icon: 'shopping_cart',
        color: '#BE185D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_convenience',
        name: '便利店',
        kind: 'expense',
        icon: 'store',
        color: '#9D174D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_street_vendor',
        name: '路边摊',
        kind: 'expense',
        icon: 'store_mall_directory',
        color: '#831843',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_farmers_market',
        name: '农贸市场',
        kind: 'expense',
        icon: 'grass',
        color: '#BE123C',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_digital',
        name: '数码',
        kind: 'expense',
        icon: 'devices',
        color: '#EC4899',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_beauty',
        name: '美妆',
        kind: 'expense',
        icon: 'spa',
        color: '#DB2777',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_gifts',
        name: '礼物',
        kind: 'expense',
        icon: 'redeem',
        color: '#BE185D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_express',
        name: '快递',
        kind: 'expense',
        icon: 'local_shipping',
        color: '#9F1239',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_secondhand',
        name: '二手交易',
        kind: 'expense',
        icon: 'recycling',
        color: '#881337',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_accessories',
        name: '配饰',
        kind: 'expense',
        icon: 'watch',
        color: '#BE185D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_jewelry',
        name: '珠宝首饰',
        kind: 'expense',
        icon: 'diamond',
        color: '#9D174D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_toys',
        name: '玩具',
        kind: 'expense',
        icon: 'toys',
        color: '#DB2777',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_books',
        name: '书刊杂志',
        kind: 'expense',
        icon: 'menu_book',
        color: '#BE185D',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_baby',
        name: '母婴用品',
        kind: 'expense',
        icon: 'child_friendly',
        color: '#EC4899',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_mall',
        name: '购物中心',
        kind: 'expense',
        icon: 'local_mall',
        color: '#DB2777',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_specialty_store',
        name: '专卖店',
        kind: 'expense',
        icon: 'storefront',
        color: '#BE123C',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_gas_station_store',
        name: '加油站便利店',
        kind: 'expense',
        icon: 'local_gas_station',
        color: '#9F1239',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_duty_free',
        name: '免税店',
        kind: 'expense',
        icon: 'flight_takeoff',
        color: '#831843',
      ),
      MoneySubCategorySeed(
        id: 'expense_shopping_flea_market',
        name: '跳蚤市场',
        kind: 'expense',
        icon: 'store',
        color: '#881337',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_housing',
    name: '居住缴费',
    kind: 'expense',
    icon: 'home',
    color: '#6366F1',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_housing_rent',
        name: '房租',
        kind: 'expense',
        icon: 'apartment',
        color: '#A5B4FC',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_mortgage',
        name: '房贷',
        kind: 'expense',
        icon: 'real_estate_agent',
        color: '#818CF8',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_utilities',
        name: '水电燃气',
        kind: 'expense',
        icon: 'bolt',
        color: '#6366F1',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_property',
        name: '物业',
        kind: 'expense',
        icon: 'domain',
        color: '#4F46E5',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_supplies',
        name: '家居用品',
        kind: 'expense',
        icon: 'chair',
        color: '#4338CA',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_electricity',
        name: '电费',
        kind: 'expense',
        icon: 'lightbulb',
        color: '#312E81',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_water',
        name: '水费',
        kind: 'expense',
        icon: 'water_drop',
        color: '#3730A3',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_gas',
        name: '燃气费',
        kind: 'expense',
        icon: 'local_fire_department',
        color: '#4338CA',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_internet',
        name: '宽带',
        kind: 'expense',
        icon: 'wifi',
        color: '#4F46E5',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_phone',
        name: '话费',
        kind: 'expense',
        icon: 'phone_iphone',
        color: '#6366F1',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_heating',
        name: '取暖费',
        kind: 'expense',
        icon: 'device_thermostat',
        color: '#818CF8',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_garbage',
        name: '垃圾清运',
        kind: 'expense',
        icon: 'delete',
        color: '#6366F1',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_solar',
        name: '光伏设备',
        kind: 'expense',
        icon: 'solar_power',
        color: '#4F46E5',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_appliances',
        name: '家用电器',
        kind: 'expense',
        icon: 'tv',
        color: '#4338CA',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_decor',
        name: '家居装饰',
        kind: 'expense',
        icon: 'imagesearch_roller',
        color: '#3730A3',
      ),
      MoneySubCategorySeed(
        id: 'expense_housing_gardening',
        name: '园艺',
        kind: 'expense',
        icon: 'yard',
        color: '#312E81',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_health',
    name: '医疗健康',
    kind: 'expense',
    icon: 'local_hospital',
    color: '#10B981',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_health_hospital',
        name: '门诊挂号',
        kind: 'expense',
        icon: 'medical_services',
        color: '#6EE7B7',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_medicine',
        name: '药品',
        kind: 'expense',
        icon: 'medication',
        color: '#34D399',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_checkup',
        name: '体检',
        kind: 'expense',
        icon: 'health_and_safety',
        color: '#10B981',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_fitness',
        name: '运动健身',
        kind: 'expense',
        icon: 'fitness_center',
        color: '#059669',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_insurance',
        name: '保险',
        kind: 'expense',
        icon: 'verified_user',
        color: '#047857',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_hospitalization',
        name: '住院',
        kind: 'expense',
        icon: 'local_hotel',
        color: '#065F46',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_dental',
        name: '牙科',
        kind: 'expense',
        icon: 'dentistry',
        color: '#047857',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_vaccination',
        name: '疫苗',
        kind: 'expense',
        icon: 'vaccines',
        color: '#059669',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_rehabilitation',
        name: '康复理疗',
        kind: 'expense',
        icon: 'accessibility_new',
        color: '#10B981',
      ),
      MoneySubCategorySeed(
        id: 'expense_health_equipment',
        name: '医疗器材',
        kind: 'expense',
        icon: 'health_and_safety',
        color: '#34D399',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_entertainment',
    name: '娱乐',
    kind: 'expense',
    icon: 'sports_esports',
    color: '#8B5CF6',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_entertainment_movies',
        name: '电影演出',
        kind: 'expense',
        icon: 'theaters',
        color: '#C4B5FD',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_games',
        name: '游戏',
        kind: 'expense',
        icon: 'sports_esports',
        color: '#A78BFA',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_theater',
        name: '剧院戏剧',
        kind: 'expense',
        icon: 'theater_comedy',
        color: '#A78BFA',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_exhibition',
        name: '展览',
        kind: 'expense',
        icon: 'museum',
        color: '#8B5CF6',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_books',
        name: '书影音',
        kind: 'expense',
        icon: 'menu_book',
        color: '#8B5CF6',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_subscriptions',
        name: '会员订阅',
        kind: 'expense',
        icon: 'subscriptions',
        color: '#7C3AED',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_streaming',
        name: '流媒体',
        kind: 'expense',
        icon: 'live_tv',
        color: '#7C3AED',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_esports',
        name: '电竞',
        kind: 'expense',
        icon: 'emoji_events',
        color: '#6D28D9',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_social',
        name: '社交聚会',
        kind: 'expense',
        icon: 'groups',
        color: '#6D28D9',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_concerts',
        name: '演出',
        kind: 'expense',
        icon: 'mic',
        color: '#5B21B6',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_karaoke',
        name: 'KTV',
        kind: 'expense',
        icon: 'music_note',
        color: '#4C1D95',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_amusement',
        name: '游乐园',
        kind: 'expense',
        icon: 'attractions',
        color: '#6D28D9',
      ),
      MoneySubCategorySeed(
        id: 'expense_entertainment_hobby',
        name: '兴趣爱好',
        kind: 'expense',
        icon: 'palette',
        color: '#7C3AED',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_education',
    name: '教育',
    kind: 'expense',
    icon: 'school',
    color: '#14B8A6',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_education_courses',
        name: '课程',
        kind: 'expense',
        icon: 'cast_for_education',
        color: '#5EEAD4',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_tuition',
        name: '学费',
        kind: 'expense',
        icon: 'account_balance',
        color: '#99F6E4',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_books',
        name: '教材书籍',
        kind: 'expense',
        icon: 'auto_stories',
        color: '#2DD4BF',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_exams',
        name: '考试认证',
        kind: 'expense',
        icon: 'assignment',
        color: '#14B8A6',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_tools',
        name: '学习工具',
        kind: 'expense',
        icon: 'laptop_mac',
        color: '#0D9488',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_study_abroad',
        name: '留学',
        kind: 'expense',
        icon: 'flight_takeoff',
        color: '#0F766E',
      ),
      MoneySubCategorySeed(
        id: 'expense_education_tutoring',
        name: '辅导补课',
        kind: 'expense',
        icon: 'co_present',
        color: '#115E59',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_travel',
    name: '旅行',
    kind: 'expense',
    icon: 'flight_takeoff',
    color: '#06B6D4',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_travel_transport',
        name: '交通票务',
        kind: 'expense',
        icon: 'confirmation_number',
        color: '#67E8F9',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_hotel',
        name: '住宿',
        kind: 'expense',
        icon: 'hotel',
        color: '#22D3EE',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_air_ticket',
        name: '机票',
        kind: 'expense',
        icon: 'flight',
        color: '#06B6D4',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_food',
        name: '旅行餐饮',
        kind: 'expense',
        icon: 'local_dining',
        color: '#06B6D4',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_tickets',
        name: '门票',
        kind: 'expense',
        icon: 'attractions',
        color: '#0891B2',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_shopping',
        name: '旅行购物',
        kind: 'expense',
        icon: 'luggage',
        color: '#0E7490',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_package',
        name: '旅游套餐',
        kind: 'expense',
        icon: 'map',
        color: '#155E75',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_visa',
        name: '签证',
        kind: 'expense',
        icon: 'badge',
        color: '#164E63',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_souvenir',
        name: '旅行纪念品',
        kind: 'expense',
        icon: 'card_giftcard',
        color: '#0891B2',
      ),
      MoneySubCategorySeed(
        id: 'expense_travel_guide',
        name: '导游服务',
        kind: 'expense',
        icon: 'record_voice_over',
        color: '#0E7490',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_subscription',
    name: '订阅服务',
    kind: 'expense',
    icon: 'subscriptions',
    color: '#0D9488',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_subscription_software',
        name: '软件订阅',
        kind: 'expense',
        icon: 'apps',
        color: '#5EEAD4',
      ),
      MoneySubCategorySeed(
        id: 'expense_subscription_cloud',
        name: '云存储',
        kind: 'expense',
        icon: 'cloud',
        color: '#2DD4BF',
      ),
      MoneySubCategorySeed(
        id: 'expense_subscription_streaming',
        name: '视频音乐会员',
        kind: 'expense',
        icon: 'play_circle',
        color: '#14B8A6',
      ),
      MoneySubCategorySeed(
        id: 'expense_subscription_knowledge',
        name: '知识付费',
        kind: 'expense',
        icon: 'school',
        color: '#0D9488',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_gift',
    name: '人情礼金',
    kind: 'expense',
    icon: 'redeem',
    color: '#F43F5E',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_gift_red_packet',
        name: '发红包',
        kind: 'expense',
        icon: 'payments',
        color: '#FDA4AF',
      ),
      MoneySubCategorySeed(
        id: 'expense_gift_sent',
        name: '送礼',
        kind: 'expense',
        icon: 'card_giftcard',
        color: '#FB7185',
      ),
      MoneySubCategorySeed(
        id: 'expense_gift_charity',
        name: '慈善捐赠',
        kind: 'expense',
        icon: 'volunteer_activism',
        color: '#F43F5E',
      ),
      MoneySubCategorySeed(
        id: 'expense_gift_business',
        name: '商务礼品',
        kind: 'expense',
        icon: 'business_center',
        color: '#E11D48',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_insurance',
    name: '保险',
    kind: 'expense',
    icon: 'shield',
    color: '#2563EB',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_insurance_health',
        name: '健康保险',
        kind: 'expense',
        icon: 'health_and_safety',
        color: '#93C5FD',
      ),
      MoneySubCategorySeed(
        id: 'expense_insurance_car',
        name: '车险',
        kind: 'expense',
        icon: 'directions_car',
        color: '#60A5FA',
      ),
      MoneySubCategorySeed(
        id: 'expense_insurance_life',
        name: '人寿保险',
        kind: 'expense',
        icon: 'favorite',
        color: '#3B82F6',
      ),
      MoneySubCategorySeed(
        id: 'expense_insurance_property',
        name: '财产险',
        kind: 'expense',
        icon: 'home',
        color: '#2563EB',
      ),
      MoneySubCategorySeed(
        id: 'expense_insurance_travel',
        name: '旅行保险',
        kind: 'expense',
        icon: 'flight_takeoff',
        color: '#1D4ED8',
      ),
      MoneySubCategorySeed(
        id: 'expense_insurance_pet',
        name: '宠物保险',
        kind: 'expense',
        icon: 'pets',
        color: '#1E40AF',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_pet',
    name: '宠物',
    kind: 'expense',
    icon: 'pets',
    color: '#65A30D',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_pet_food',
        name: '宠物食品',
        kind: 'expense',
        icon: 'pets',
        color: '#BEF264',
      ),
      MoneySubCategorySeed(
        id: 'expense_pet_vet',
        name: '宠物医疗',
        kind: 'expense',
        icon: 'medical_services',
        color: '#A3E635',
      ),
      MoneySubCategorySeed(
        id: 'expense_pet_grooming',
        name: '宠物美容',
        kind: 'expense',
        icon: 'content_cut',
        color: '#84CC16',
      ),
      MoneySubCategorySeed(
        id: 'expense_pet_toys',
        name: '宠物玩具',
        kind: 'expense',
        icon: 'toys',
        color: '#84CC16',
      ),
      MoneySubCategorySeed(
        id: 'expense_pet_boarding',
        name: '宠物寄养',
        kind: 'expense',
        icon: 'home',
        color: '#65A30D',
      ),
      MoneySubCategorySeed(
        id: 'expense_pet_supplies',
        name: '宠物用品',
        kind: 'expense',
        icon: 'inventory_2',
        color: '#65A30D',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_business',
    name: '商务支出',
    kind: 'expense',
    icon: 'business_center',
    color: '#9333EA',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_business_office_supplies',
        name: '办公用品',
        kind: 'expense',
        icon: 'inventory_2',
        color: '#D8B4FE',
      ),
      MoneySubCategorySeed(
        id: 'expense_business_equipment',
        name: '设备采购',
        kind: 'expense',
        icon: 'devices',
        color: '#C084FC',
      ),
      MoneySubCategorySeed(
        id: 'expense_business_travel',
        name: '商务差旅',
        kind: 'expense',
        icon: 'flight_takeoff',
        color: '#A855F7',
      ),
      MoneySubCategorySeed(
        id: 'expense_business_marketing',
        name: '市场营销',
        kind: 'expense',
        icon: 'campaign',
        color: '#9333EA',
      ),
      MoneySubCategorySeed(
        id: 'expense_business_consulting',
        name: '咨询服务',
        kind: 'expense',
        icon: 'support_agent',
        color: '#7E22CE',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_charity',
    name: '公益慈善',
    kind: 'expense',
    icon: 'volunteer_activism',
    color: '#E11D48',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_charity_donation',
        name: '现金捐赠',
        kind: 'expense',
        icon: 'payments',
        color: '#FDA4AF',
      ),
      MoneySubCategorySeed(
        id: 'expense_charity_material',
        name: '物资捐赠',
        kind: 'expense',
        icon: 'inventory_2',
        color: '#FB7185',
      ),
      MoneySubCategorySeed(
        id: 'expense_charity_project',
        name: '项目支持',
        kind: 'expense',
        icon: 'eco',
        color: '#F43F5E',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_family',
    name: '家庭',
    kind: 'expense',
    icon: 'family_restroom',
    color: '#84CC16',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_family_children',
        name: '子女',
        kind: 'expense',
        icon: 'child_care',
        color: '#BEF264',
      ),
      MoneySubCategorySeed(
        id: 'expense_family_parents',
        name: '父母',
        kind: 'expense',
        icon: 'elderly',
        color: '#A3E635',
      ),
      MoneySubCategorySeed(
        id: 'expense_family_pets',
        name: '宠物',
        kind: 'expense',
        icon: 'pets',
        color: '#84CC16',
      ),
      MoneySubCategorySeed(
        id: 'expense_family_allowance',
        name: '家庭零用',
        kind: 'expense',
        icon: 'account_balance_wallet',
        color: '#65A30D',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'system_transfer',
    name: '转账',
    kind: 'expense',
    icon: 'swap_horiz',
    color: '#64748B',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_transfer_account',
        name: '账户间转账',
        kind: 'expense',
        icon: 'swap_horiz',
        color: '#CBD5E1',
      ),
      MoneySubCategorySeed(
        id: 'expense_transfer_family',
        name: '亲友转账',
        kind: 'expense',
        icon: 'groups',
        color: '#94A3B8',
      ),
      MoneySubCategorySeed(
        id: 'expense_transfer_credit_card',
        name: '信用卡还款',
        kind: 'expense',
        icon: 'credit_card',
        color: '#64748B',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_loan',
    name: '贷款还款',
    kind: 'expense',
    icon: 'account_balance',
    color: '#7C2D12',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_loan_mortgage',
        name: '房贷月供',
        kind: 'expense',
        icon: 'real_estate_agent',
        color: '#FDBA74',
      ),
      MoneySubCategorySeed(
        id: 'expense_loan_car',
        name: '车贷还款',
        kind: 'expense',
        icon: 'directions_car',
        color: '#FB923C',
      ),
      MoneySubCategorySeed(
        id: 'expense_loan_personal',
        name: '消费贷款',
        kind: 'expense',
        icon: 'request_quote',
        color: '#F97316',
      ),
      MoneySubCategorySeed(
        id: 'expense_loan_credit_card',
        name: '信用卡还款',
        kind: 'expense',
        icon: 'credit_card',
        color: '#EA580C',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'expense_other',
    name: '其他支出',
    kind: 'expense',
    icon: 'more_horiz',
    color: '#64748B',
    subCategories: [
      MoneySubCategorySeed(
        id: 'expense_other_fees',
        name: '手续费',
        kind: 'expense',
        icon: 'receipt_long',
        color: '#CBD5E1',
      ),
      MoneySubCategorySeed(
        id: 'expense_other_donations',
        name: '捐赠',
        kind: 'expense',
        icon: 'volunteer_activism',
        color: '#94A3B8',
      ),
      MoneySubCategorySeed(
        id: 'expense_other_losses',
        name: '损失',
        kind: 'expense',
        icon: 'warning',
        color: '#64748B',
      ),
      MoneySubCategorySeed(
        id: 'expense_other_misc',
        name: '杂项',
        kind: 'expense',
        icon: 'category',
        color: '#475569',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_salary',
    name: '工资',
    kind: 'income',
    icon: 'payments',
    color: '#22C55E',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_salary_base',
        name: '基本工资',
        kind: 'income',
        icon: 'account_balance',
        color: '#86EFAC',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_overtime',
        name: '加班费',
        kind: 'income',
        icon: 'schedule',
        color: '#4ADE80',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_allowance',
        name: '补贴',
        kind: 'income',
        icon: 'add_card',
        color: '#22C55E',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_reimbursement',
        name: '报销',
        kind: 'income',
        icon: 'request_quote',
        color: '#16A34A',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_commission',
        name: '提成',
        kind: 'income',
        icon: 'trending_up',
        color: '#15803D',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_pension',
        name: '养老金',
        kind: 'income',
        icon: 'elderly',
        color: '#166534',
      ),
      MoneySubCategorySeed(
        id: 'income_salary_part_time',
        name: '兼职收入',
        kind: 'income',
        icon: 'work',
        color: '#14532D',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_bonus',
    name: '奖金',
    kind: 'income',
    icon: 'workspace_premium',
    color: '#EAB308',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_bonus_performance',
        name: '绩效奖金',
        kind: 'income',
        icon: 'emoji_events',
        color: '#FDE68A',
      ),
      MoneySubCategorySeed(
        id: 'income_bonus_annual',
        name: '年终奖',
        kind: 'income',
        icon: 'celebration',
        color: '#FACC15',
      ),
      MoneySubCategorySeed(
        id: 'income_bonus_project',
        name: '项目奖金',
        kind: 'income',
        icon: 'task_alt',
        color: '#EAB308',
      ),
      MoneySubCategorySeed(
        id: 'income_bonus_commission',
        name: '提成',
        kind: 'income',
        icon: 'trending_up',
        color: '#CA8A04',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_investment',
    name: '投资收益',
    kind: 'income',
    icon: 'show_chart',
    color: '#3B82F6',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_investment_interest',
        name: '利息',
        kind: 'income',
        icon: 'savings',
        color: '#93C5FD',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_dividend',
        name: '分红',
        kind: 'income',
        icon: 'donut_large',
        color: '#60A5FA',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_fund',
        name: '基金收益',
        kind: 'income',
        icon: 'query_stats',
        color: '#3B82F6',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_stock',
        name: '股票收益',
        kind: 'income',
        icon: 'candlestick_chart',
        color: '#2563EB',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_rent',
        name: '租金收入',
        kind: 'income',
        icon: 'house',
        color: '#1D4ED8',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_capital_gain',
        name: '资本利得',
        kind: 'income',
        icon: 'stacked_line_chart',
        color: '#1E40AF',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_crypto',
        name: '加密货币收益',
        kind: 'income',
        icon: 'currency_bitcoin',
        color: '#1E3A8A',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_royalties',
        name: '版权收入',
        kind: 'income',
        icon: 'copyright',
        color: '#1E40AF',
      ),
      MoneySubCategorySeed(
        id: 'income_investment_reinvestment',
        name: '分红再投',
        kind: 'income',
        icon: 'sync',
        color: '#1E3A8A',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_savings',
    name: '储蓄收益',
    kind: 'income',
    icon: 'savings',
    color: '#0891B2',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_savings_bank_interest',
        name: '银行利息',
        kind: 'income',
        icon: 'account_balance',
        color: '#67E8F9',
      ),
      MoneySubCategorySeed(
        id: 'income_savings_fixed_deposit',
        name: '定期存款',
        kind: 'income',
        icon: 'calendar_month',
        color: '#22D3EE',
      ),
      MoneySubCategorySeed(
        id: 'income_savings_money_market',
        name: '货币基金',
        kind: 'income',
        icon: 'savings',
        color: '#06B6D4',
      ),
      MoneySubCategorySeed(
        id: 'income_savings_short_bond',
        name: '短债收益',
        kind: 'income',
        icon: 'show_chart',
        color: '#0891B2',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_gift',
    name: '礼金',
    kind: 'income',
    icon: 'card_giftcard',
    color: '#F43F5E',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_gift_red_packet',
        name: '红包',
        kind: 'income',
        icon: 'redeem',
        color: '#FDA4AF',
      ),
      MoneySubCategorySeed(
        id: 'income_gift_received',
        name: '收礼',
        kind: 'income',
        icon: 'card_giftcard',
        color: '#FB7185',
      ),
      MoneySubCategorySeed(
        id: 'income_gift_family',
        name: '家人转账',
        kind: 'income',
        icon: 'family_restroom',
        color: '#FB7185',
      ),
      MoneySubCategorySeed(
        id: 'income_gift_wedding',
        name: '婚礼礼金',
        kind: 'income',
        icon: 'favorite',
        color: '#F43F5E',
      ),
      MoneySubCategorySeed(
        id: 'income_gift_holiday',
        name: '节日礼金',
        kind: 'income',
        icon: 'festival',
        color: '#E11D48',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_transfer',
    name: '转账',
    kind: 'income',
    icon: 'swap_horiz',
    color: '#64748B',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_transfer_account',
        name: '账户间转账',
        kind: 'income',
        icon: 'swap_horiz',
        color: '#CBD5E1',
      ),
      MoneySubCategorySeed(
        id: 'income_transfer_family',
        name: '亲友转账',
        kind: 'income',
        icon: 'groups',
        color: '#94A3B8',
      ),
      MoneySubCategorySeed(
        id: 'income_transfer_credit_card',
        name: '信用卡还款',
        kind: 'income',
        icon: 'credit_card',
        color: '#64748B',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_reimbursement',
    name: '报销',
    kind: 'income',
    icon: 'receipt_long',
    color: '#0F766E',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_reimbursement_business',
        name: '商务报销',
        kind: 'income',
        icon: 'business_center',
        color: '#5EEAD4',
      ),
      MoneySubCategorySeed(
        id: 'income_reimbursement_travel',
        name: '差旅报销',
        kind: 'income',
        icon: 'flight_takeoff',
        color: '#2DD4BF',
      ),
      MoneySubCategorySeed(
        id: 'income_reimbursement_medical',
        name: '医疗报销',
        kind: 'income',
        icon: 'local_hospital',
        color: '#14B8A6',
      ),
      MoneySubCategorySeed(
        id: 'income_reimbursement_other',
        name: '其他报销',
        kind: 'income',
        icon: 'more_horiz',
        color: '#0D9488',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_business',
    name: '经营收入',
    kind: 'income',
    icon: 'business_center',
    color: '#9333EA',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_business_service',
        name: '服务收入',
        kind: 'income',
        icon: 'handyman',
        color: '#D8B4FE',
      ),
      MoneySubCategorySeed(
        id: 'income_business_project',
        name: '项目回款',
        kind: 'income',
        icon: 'folder',
        color: '#C084FC',
      ),
      MoneySubCategorySeed(
        id: 'income_business_sales',
        name: '销售收入',
        kind: 'income',
        icon: 'sell',
        color: '#A855F7',
      ),
      MoneySubCategorySeed(
        id: 'income_business_contract',
        name: '合同收入',
        kind: 'income',
        icon: 'description',
        color: '#9333EA',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_loan',
    name: '借贷款项',
    kind: 'income',
    icon: 'account_balance',
    color: '#7C3AED',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_loan_personal',
        name: '个人借入',
        kind: 'income',
        icon: 'groups',
        color: '#C4B5FD',
      ),
      MoneySubCategorySeed(
        id: 'income_loan_bank',
        name: '银行放款',
        kind: 'income',
        icon: 'account_balance',
        color: '#A78BFA',
      ),
      MoneySubCategorySeed(
        id: 'income_loan_credit_line',
        name: '授信提款',
        kind: 'income',
        icon: 'credit_card',
        color: '#8B5CF6',
      ),
    ],
  ),
  MoneyCategorySeed(
    id: 'income_other',
    name: '其他收入',
    kind: 'income',
    icon: 'more_horiz',
    color: '#0F766E',
    subCategories: [
      MoneySubCategorySeed(
        id: 'income_other_refund',
        name: '退款',
        kind: 'income',
        icon: 'keyboard_return',
        color: '#5EEAD4',
      ),
      MoneySubCategorySeed(
        id: 'income_other_secondhand',
        name: '二手出售',
        kind: 'income',
        icon: 'sell',
        color: '#2DD4BF',
      ),
      MoneySubCategorySeed(
        id: 'income_other_part_time',
        name: '兼职',
        kind: 'income',
        icon: 'work',
        color: '#14B8A6',
      ),
      MoneySubCategorySeed(
        id: 'income_other_misc',
        name: '杂项收入',
        kind: 'income',
        icon: 'category',
        color: '#0F766E',
      ),
      MoneySubCategorySeed(
        id: 'income_other_tax_refund',
        name: '退税',
        kind: 'income',
        icon: 'receipt',
        color: '#115E59',
      ),
      MoneySubCategorySeed(
        id: 'income_other_subsidy',
        name: '补助',
        kind: 'income',
        icon: 'account_balance',
        color: '#134E4A',
      ),
      MoneySubCategorySeed(
        id: 'income_other_windfall',
        name: '意外收入',
        kind: 'income',
        icon: 'celebration',
        color: '#0F766E',
      ),
    ],
  ),
];
