//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "family_ledger")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub description: String,
    pub base_currency: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub members: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub accounts: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub transactions: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub budgets: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub audit_logs: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::BaseCurrency",
        to = "super::currency::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currency,
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
