//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::ExerciseIntensity;
use super::sea_orm_active_enums::FlowLevel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "period_daily_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub period_serial_num: String,
    pub date: Date,
    pub flow_level: Option<FlowLevel>,
    pub sexual_activity: bool,
    pub exercise_intensity: ExerciseIntensity,
    pub diet: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::period_records::Entity",
        from = "Column::PeriodSerialNum",
        to = "super::period_records::Column::SerialNum",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PeriodRecords,
    #[sea_orm(has_many = "super::period_symptoms::Entity")]
    PeriodSymptoms,
}

impl Related<super::period_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodRecords.def()
    }
}

impl Related<super::period_symptoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PeriodSymptoms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
