//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum AccountType {
    #[sea_orm(num_value = 0)]
    Cash,
    #[sea_orm(num_value = 1)]
    Bank,
    #[sea_orm(num_value = 2)]
    CreditCard,
    #[sea_orm(num_value = 3)]
    WeChat,
    #[sea_orm(num_value = 4)]
    Alipay,
    #[sea_orm(num_value = 5)]
    Investment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum ExerciseIntensity {
    #[sea_orm(num_value = 0)]
    None,
    #[sea_orm(num_value = 1)]
    Light,
    #[sea_orm(num_value = 2)]
    Medium,
    #[sea_orm(num_value = 3)]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum FlowLevel {
    #[sea_orm(num_value = 0)]
    Light,
    #[sea_orm(num_value = 1)]
    Medium,
    #[sea_orm(num_value = 2)]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum Intensity {
    #[sea_orm(num_value = 0)]
    Light,
    #[sea_orm(num_value = 1)]
    Medium,
    #[sea_orm(num_value = 2)]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum ReminderType {
    #[sea_orm(num_value = 0)]
    Notification,
    #[sea_orm(num_value = 1)]
    Email,
    #[sea_orm(num_value = 2)]
    Popup,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum RepeatPeriod {
    #[sea_orm(num_value = 0)]
    Daily,
    #[sea_orm(num_value = 1)]
    Weekly,
    #[sea_orm(num_value = 2)]
    Monthy,
    #[sea_orm(num_value = 3)]
    Quarterly,
    #[sea_orm(num_value = 4)]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum SymptomsType {
    #[sea_orm(num_value = 0)]
    Pain,
    #[sea_orm(num_value = 1)]
    Fatigue,
    #[sea_orm(num_value = 2)]
    MoodSwing,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum TransactionStatus {
    #[sea_orm(num_value = 0)]
    Pending,
    #[sea_orm(num_value = 1)]
    Completed,
    #[sea_orm(num_value = 2)]
    Reversed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum TransactionType {
    #[sea_orm(num_value = 0)]
    Income,
    #[sea_orm(num_value = 1)]
    Expense,
    #[sea_orm(num_value = 2)]
    Transfer,
    #[sea_orm(num_value = 3)]
    Reimbursement,
    #[sea_orm(num_value = 4)]
    Gift,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum UserRole {
    #[sea_orm(num_value = 0)]
    Admin,
    #[sea_orm(num_value = 1)]
    User,
    #[sea_orm(num_value = 2)]
    Moderator,
    #[sea_orm(num_value = 3)]
    Editor,
    #[sea_orm(num_value = 4)]
    Guest,
    #[sea_orm(num_value = 5)]
    Developer,
    #[sea_orm(num_value = 6)]
    Owner,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum UserStatus {
    #[sea_orm(num_value = 0)]
    Active,
    #[sea_orm(num_value = 1)]
    Inactive,
    #[sea_orm(num_value = 2)]
    Suspended,
    #[sea_orm(num_value = 3)]
    Banned,
    #[sea_orm(num_value = 4)]
    Pending,
    #[sea_orm(num_value = 5)]
    Deleted,
}
