//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Deserializer, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum AccountType {
    #[sea_orm(num_value = 0)]
    Cash, // 现金账户
    #[sea_orm(num_value = 1)]
    Bank, // 银行账户（储蓄卡）
    #[sea_orm(num_value = 2)]
    CreditCard, // 信用卡账户
    #[sea_orm(num_value = 3)]
    Investment, // 投资账户
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum PaymentMethod {
    #[sea_orm(num_value = 0)]
    Cash, // 现金支付
    #[sea_orm(num_value = 1)]
    BankTransfer, // 银行转账
    #[sea_orm(num_value = 2)]
    CreditCard, // 信用卡支付
    #[sea_orm(num_value = 3)]
    WeChat, // 微信支付
    #[sea_orm(num_value = 4)]
    Alipay, // 支付宝支付
    #[sea_orm(num_value = 5)]
    Other, // 其他支付方式
}

/// 运动强度等级
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum ExerciseIntensity {
    /// 无运动
    #[sea_orm(num_value = 0)]
    None,
    /// 轻度运动
    #[sea_orm(num_value = 1)]
    Light,
    /// 中等强度运动
    #[sea_orm(num_value = 2)]
    Medium,
    /// 高强度运动
    #[sea_orm(num_value = 3)]
    Heavy,
}

/// 经期流量等级
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum FlowLevel {
    /// 轻度流量
    #[sea_orm(num_value = 0)]
    Light,
    /// 中等流量
    #[sea_orm(num_value = 1)]
    Medium,
    /// 重度流量
    #[sea_orm(num_value = 2)]
    Heavy,
}

/// 一般强度等级
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum Intensity {
    /// 轻度
    #[sea_orm(num_value = 0)]
    Light,
    /// 中度
    #[sea_orm(num_value = 1)]
    Medium,
    /// 重度
    #[sea_orm(num_value = 2)]
    Heavy,
}

/// 提醒类型
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum ReminderType {
    /// 系统通知提醒
    #[sea_orm(num_value = 0)]
    Notification,
    /// 邮件提醒
    #[sea_orm(num_value = 1)]
    Email,
    /// 弹窗提醒
    #[sea_orm(num_value = 2)]
    Popup,
}

/// 重复周期
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum RepeatPeriod {
    /// 每日
    #[sea_orm(num_value = 0)]
    Daily,
    /// 每周
    #[sea_orm(num_value = 1)]
    Weekly,
    /// 每月
    #[sea_orm(num_value = 2)]
    Monthy,
    /// 每季度
    #[sea_orm(num_value = 3)]
    Quarterly,
    /// 每年
    #[sea_orm(num_value = 4)]
    Yearly,
}

/// 症状类型
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum SymptomsType {
    /// 疼痛
    #[sea_orm(num_value = 0)]
    Pain,
    /// 疲劳
    #[sea_orm(num_value = 1)]
    Fatigue,
    /// 情绪波动
    #[sea_orm(num_value = 2)]
    MoodSwing,
}

/// 交易状态
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum TransactionStatus {
    /// 待处理
    #[sea_orm(num_value = 0)]
    Pending,
    /// 已完成
    #[sea_orm(num_value = 1)]
    Completed,
    /// 已冲销
    #[sea_orm(num_value = 2)]
    Reversed,
}

/// 交易类型
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum TransactionType {
    /// 收入
    #[sea_orm(num_value = 0)]
    Income,
    /// 支出
    #[sea_orm(num_value = 1)]
    Expense,
    /// 转账
    #[sea_orm(num_value = 2)]
    Transfer,
    /// 报销
    #[sea_orm(num_value = 3)]
    Reimbursement,
    /// 礼物
    #[sea_orm(num_value = 4)]
    Gift,
}
// 交易分类
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum Category {
    #[sea_orm(num_value = 0)]
    Food, // 食物
    #[sea_orm(num_value = 1)]
    Transport, // 交通
    #[sea_orm(num_value = 2)]
    Entertainment, // 娱乐
    #[sea_orm(num_value = 3)]
    Utilities, // 水电煤气等公共事业
    #[sea_orm(num_value = 4)]
    Shopping, // 购物
    #[sea_orm(num_value = 5)]
    Salary, // 工资收入
    #[sea_orm(num_value = 6)]
    Investment, // 投资理财
    #[sea_orm(num_value = 7)]
    Others, // 其他
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum SubCategory {
    // 食物类子分类
    #[sea_orm(num_value = 0)]
    Restaurant,
    #[sea_orm(num_value = 1)]
    Groceries,
    #[sea_orm(num_value = 2)]
    Snacks,

    // 交通类子分类
    #[sea_orm(num_value = 10)]
    Bus,
    #[sea_orm(num_value = 11)]
    Taxi,
    #[sea_orm(num_value = 12)]
    Fuel,

    // 娱乐类子分类
    #[sea_orm(num_value = 20)]
    Movies,
    #[sea_orm(num_value = 21)]
    Concerts,

    // 工资收入类子分类
    #[sea_orm(num_value = 30)]
    MonthlySalary,
    #[sea_orm(num_value = 31)]
    Bonus,

    // 其他
    #[sea_orm(num_value = 99)]
    Other,
}

/// 用户角色
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum UserRole {
    /// 管理员
    #[sea_orm(num_value = 0)]
    Admin,
    /// 普通用户
    #[sea_orm(num_value = 1)]
    User,
    /// 版主
    #[sea_orm(num_value = 2)]
    Moderator,
    /// 编辑
    #[sea_orm(num_value = 3)]
    Editor,
    /// 访客
    #[sea_orm(num_value = 4)]
    Guest,
    /// 开发者
    #[sea_orm(num_value = 5)]
    Developer,
    /// 所有者
    #[sea_orm(num_value = 6)]
    Owner,
}

/// 用户状态
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i16", db_type = "Integer")]
pub enum UserStatus {
    /// 活跃
    #[sea_orm(num_value = 0)]
    Active,
    /// 不活跃
    #[sea_orm(num_value = 1)]
    Inactive,
    /// 暂停
    #[sea_orm(num_value = 2)]
    Suspended,
    /// 封禁
    #[sea_orm(num_value = 3)]
    Banned,
    /// 待审核
    #[sea_orm(num_value = 4)]
    Pending,
    /// 已删除
    #[sea_orm(num_value = 5)]
    Deleted,
}

/// 优先级
#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "i16", db_type = "SmallInteger")]
pub enum Priority {
    /// 低优先级
    #[sea_orm(num_value = 0)]
    Low,
    /// 中优先级
    #[sea_orm(num_value = 1)]
    Medium,
    /// 高优先级
    #[sea_orm(num_value = 2)]
    High,
    /// 紧急优先级
    #[sea_orm(num_value = 3)]
    Urgent,
}

/// 任务状态
#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "i16", db_type = "SmallInteger")]
pub enum Status {
    /// 未开始
    #[sea_orm(num_value = 0)]
    NotStarted,
    /// 进行中
    #[sea_orm(num_value = 1)]
    InProgress,
    /// 已完成
    #[sea_orm(num_value = 2)]
    Completed,
    /// 已取消
    #[sea_orm(num_value = 3)]
    Cancelled,
    /// 已逾期
    #[sea_orm(num_value = 4)]
    Overdue,
}

impl From<Priority> for i8 {
    fn from(value: Priority) -> Self {
        value as i8
    }
}

impl From<Status> for i8 {
    fn from(value: Status) -> Self {
        value as i8
    }
}
impl<'de> Deserialize<'de> for Priority {
    fn deserialize<D>(deserializer: D) -> Result<Priority, D::Error>
    where
        D: Deserializer<'de>,
    {
        let v = i8::deserialize(deserializer)?;
        match v {
            0 => Ok(Priority::Low),
            1 => Ok(Priority::Medium),
            2 => Ok(Priority::High),
            3 => Ok(Priority::Urgent),
            _ => Ok(Priority::Low),
        }
    }
}
impl<'de> Deserialize<'de> for Status {
    fn deserialize<D>(deserializer: D) -> Result<Status, D::Error>
    where
        D: Deserializer<'de>,
    {
        let v = i8::deserialize(deserializer)?;
        match v {
            0 => Ok(Status::NotStarted),
            1 => Ok(Status::InProgress),
            2 => Ok(Status::Completed),
            3 => Ok(Status::Cancelled),
            4 => Ok(Status::Overdue),
            _ => Ok(Status::NotStarted),
        }
    }
}
