//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_type")]
pub enum AccountType {
    #[sea_orm(string_value = "Cash")]
    Cash,
    #[sea_orm(string_value = "Bank")]
    Bank,
    #[sea_orm(string_value = "CreditCard")]
    CreditCard,
    #[sea_orm(string_value = "WeChat")]
    WeChat,
    #[sea_orm(string_value = "Alipay")]
    Alipay,
    #[sea_orm(string_value = "Investment")]
    Investment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "exercise_intensity")]
pub enum ExerciseIntensity {
    #[sea_orm(string_value = "None")]
    None,
    #[sea_orm(string_value = "Light")]
    Light,
    #[sea_orm(string_value = "Medium")]
    Medium,
    #[sea_orm(string_value = "Heavy")]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "flow_level")]
pub enum FlowLevel {
    #[sea_orm(string_value = "Light")]
    Light,
    #[sea_orm(string_value = "Medium")]
    Medium,
    #[sea_orm(string_value = "Heavy")]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "intensity")]
pub enum Intensity {
    #[sea_orm(string_value = "Light")]
    Light,
    #[sea_orm(string_value = "Medium")]
    Medium,
    #[sea_orm(string_value = "Heavy")]
    Heavy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "reminder_type")]
pub enum ReminderType {
    #[sea_orm(string_value = "notification")]
    Notification,
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "popup")]
    Popup,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "repeat_period")]
pub enum RepeatPeriod {
    #[sea_orm(string_value = "Daily")]
    Daily,
    #[sea_orm(string_value = "Weekly")]
    Weekly,
    #[sea_orm(string_value = "Monthy")]
    Monthy,
    #[sea_orm(string_value = "Quarterly")]
    Quarterly,
    #[sea_orm(string_value = "Yearly")]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "symptoms_type")]
pub enum SymptomsType {
    #[sea_orm(string_value = "Pain")]
    Pain,
    #[sea_orm(string_value = "Fatigue")]
    Fatigue,
    #[sea_orm(string_value = "MoodSwing")]
    MoodSwing,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_status")]
pub enum TransactionStatus {
    #[sea_orm(string_value = "Pending")]
    Pending,
    #[sea_orm(string_value = "Completed")]
    Completed,
    #[sea_orm(string_value = "Reversed")]
    Reversed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_type")]
pub enum TransactionType {
    #[sea_orm(string_value = "Income")]
    Income,
    #[sea_orm(string_value = "Expense")]
    Expense,
    #[sea_orm(string_value = "Transfer")]
    Transfer,
    #[sea_orm(string_value = "Reimbursement")]
    Reimbursement,
    #[sea_orm(string_value = "Gift")]
    Gift,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "moderator")]
    Moderator,
    #[sea_orm(string_value = "editor")]
    Editor,
    #[sea_orm(string_value = "guest")]
    Guest,
    #[sea_orm(string_value = "developer")]
    Developer,
    #[sea_orm(string_value = "owner")]
    Owner,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "suspended")]
    Suspended,
    #[sea_orm(string_value = "banned")]
    Banned,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "deleted")]
    Deleted,
}
