//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::entity::sea_orm_active_enums::{
    AccountType, Category, PaymentMethod, TransactionStatus, TransactionType,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    pub transaction_type: TransactionType,
    pub transaction_status: TransactionStatus,
    pub date: Date,
    pub amount: Decimal,
    pub currency: String,
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub account_serial_num: String,
    pub category: Category,
    pub sub_category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub split_members: Option<Json>,
    pub payment_method: PaymentMethod,
    pub actual_payer_account: AccountType,
    pub create_at: DateTimeWithTimeZone,
    pub update_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountSerialNum",
        to = "super::account::Column::SerialNum",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Account,
    #[sea_orm(has_many = "super::bil_reminder::Entity")]
    BilReminder,
    #[sea_orm(
        belongs_to = "super::currency::Entity",
        from = "Column::Currency",
        to = "super::currency::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Currency,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::bil_reminder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BilReminder.def()
    }
}

impl Related<super::currency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Currency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
