//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::entity::sea_orm_active_enums::{UserRole, UserStatus};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub serial_num: String,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub phone: Option<String>,
    pub password_hash: String,
    pub avatar_url: Option<String>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub is_verified: bool,
    pub role: UserRole,
    pub status: UserStatus,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub phone_verified_at: Option<DateTimeWithTimeZone>,
    pub bio: Option<String>,
    pub language: Option<String>,
    pub timezone: Option<String>,
    pub last_active_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account::Entity")]
    Account,
    #[sea_orm(has_many = "super::todo::Entity")]
    Todo,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::todo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Todo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
