/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
  const CrudActionErrorCode: typeof import('./composables/useCrudActions')['CrudActionErrorCode'];
  const EffectScope: typeof import('vue')['EffectScope'];
  const HealthDbError: typeof import('./stores/periodStore')['HealthDbError'];
  const HealthStoreErrorCode: typeof import('./stores/periodStore')['HealthStoreErrorCode'];
  const MEDIA_BREAKPOINTS: typeof import('./stores/mediaQueries')['MEDIA_BREAKPOINTS'];
  const MoneyStoreError: typeof import('./stores/moneyStore')['MoneyStoreError'];
  const MoneyStoreErrorCode: typeof import('./stores/moneyStore')['MoneyStoreErrorCode'];
  const SplitType: typeof import('./composables/useSplitCalculator')['SplitType'];
  const TodoStoreErrorCode: typeof import('./stores/todoStore')['TodoStoreErrorCode'];
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate'];
  const asyncComputed: typeof import('@vueuse/core')['asyncComputed'];
  const authStore: typeof import('./stores/auth')['authStore'];
  const autoResetRef: typeof import('@vueuse/core')['autoResetRef'];
  const clearAllSettingsCache: typeof import('./composables/useSettingsCache')['clearAllSettingsCache'];
  const compareTodos: typeof import('./stores/todoStore')['compareTodos'];
  const computed: typeof import('vue')['computed'];
  const computedAsync: typeof import('@vueuse/core')['computedAsync'];
  const computedEager: typeof import('@vueuse/core')['computedEager'];
  const computedInject: typeof import('@vueuse/core')['computedInject'];
  const computedWithControl: typeof import('@vueuse/core')['computedWithControl'];
  const controlledComputed: typeof import('@vueuse/core')['controlledComputed'];
  const controlledRef: typeof import('@vueuse/core')['controlledRef'];
  const createApp: typeof import('vue')['createApp'];
  const createDatabaseSetting: typeof import('./composables/useAutoSaveSettings')['createDatabaseSetting'];
  const createEventHook: typeof import('@vueuse/core')['createEventHook'];
  const createFieldValidator: typeof import('./composables/useFormValidation')['createFieldValidator'];
  const createGlobalState: typeof import('@vueuse/core')['createGlobalState'];
  const createInjectionState: typeof import('@vueuse/core')['createInjectionState'];
  const createPinia: typeof import('pinia')['createPinia'];
  const createReactiveFn: typeof import('@vueuse/core')['createReactiveFn'];
  const createRef: typeof import('@vueuse/core')['createRef'];
  const createReusableTemplate: typeof import('@vueuse/core')['createReusableTemplate'];
  const createSharedComposable: typeof import('@vueuse/core')['createSharedComposable'];
  const createSimpleSetting: typeof import('./composables/useAutoSaveSettings')['createSimpleSetting'];
  const createTauriSetting: typeof import('./composables/useAutoSaveSettings')['createTauriSetting'];
  const createTemplatePromise: typeof import('@vueuse/core')['createTemplatePromise'];
  const createUnrefFn: typeof import('@vueuse/core')['createUnrefFn'];
  const customRef: typeof import('vue')['customRef'];
  const debouncedRef: typeof import('@vueuse/core')['debouncedRef'];
  const debouncedWatch: typeof import('@vueuse/core')['debouncedWatch'];
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent'];
  const defineComponent: typeof import('vue')['defineComponent'];
  const defineStore: typeof import('pinia')['defineStore'];
  const eagerComputed: typeof import('@vueuse/core')['eagerComputed'];
  const effectScope: typeof import('vue')['effectScope'];
  const extendRef: typeof import('@vueuse/core')['extendRef'];
  const getActivePinia: typeof import('pinia')['getActivePinia'];
  const getBrowserLocale: typeof import('./stores/locales')['getBrowserLocale'];
  const getCurrentInstance: typeof import('vue')['getCurrentInstance'];
  const getCurrentLocale: typeof import('./stores/locales')['getCurrentLocale'];
  const getCurrentScope: typeof import('vue')['getCurrentScope'];
  const getCurrentTheme: typeof import('./stores/theme')['getCurrentTheme'];
  const getCurrentUser: typeof import('./stores/auth')['getCurrentUser'];
  const getLocaleFlag: typeof import('./stores/locales')['getLocaleFlag'];
  const getLocaleName: typeof import('./stores/locales')['getLocaleName'];
  const getSettingsCacheManager: typeof import('./composables/useSettingsCache')['getSettingsCacheManager'];
  const getSupportedLocales: typeof import('./stores/locales')['getSupportedLocales'];
  const h: typeof import('vue')['h'];
  const ignorableWatch: typeof import('@vueuse/core')['ignorableWatch'];
  const inject: typeof import('vue')['inject'];
  const injectLocal: typeof import('@vueuse/core')['injectLocal'];
  const isAuthenticated: typeof import('./stores/auth')['isAuthenticated'];
  const isDefined: typeof import('@vueuse/core')['isDefined'];
  const isProxy: typeof import('vue')['isProxy'];
  const isReactive: typeof import('vue')['isReactive'];
  const isReadonly: typeof import('vue')['isReadonly'];
  const isRef: typeof import('vue')['isRef'];
  const isSupportedLocale: typeof import('./stores/locales')['isSupportedLocale'];
  const localeState: typeof import('./stores/locales')['localeState'];
  const localeStore: typeof import('./stores/locales')['localeStore'];
  const loginUser: typeof import('./stores/auth')['loginUser'];
  const logoutUser: typeof import('./stores/auth')['logoutUser'];
  const makeDestructurable: typeof import('@vueuse/core')['makeDestructurable'];
  const mapActions: typeof import('pinia')['mapActions'];
  const mapGetters: typeof import('pinia')['mapGetters'];
  const mapState: typeof import('pinia')['mapState'];
  const mapStores: typeof import('pinia')['mapStores'];
  const mapWritableState: typeof import('pinia')['mapWritableState'];
  const markRaw: typeof import('vue')['markRaw'];
  const nextTick: typeof import('vue')['nextTick'];
  const onActivated: typeof import('vue')['onActivated'];
  const onBeforeMount: typeof import('vue')['onBeforeMount'];
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave'];
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate'];
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount'];
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate'];
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside'];
  const onDeactivated: typeof import('vue')['onDeactivated'];
  const onElementRemoval: typeof import('@vueuse/core')['onElementRemoval'];
  const onErrorCaptured: typeof import('vue')['onErrorCaptured'];
  const onKeyStroke: typeof import('@vueuse/core')['onKeyStroke'];
  const onLongPress: typeof import('@vueuse/core')['onLongPress'];
  const onMounted: typeof import('vue')['onMounted'];
  const onRenderTracked: typeof import('vue')['onRenderTracked'];
  const onRenderTriggered: typeof import('vue')['onRenderTriggered'];
  const onScopeDispose: typeof import('vue')['onScopeDispose'];
  const onServerPrefetch: typeof import('vue')['onServerPrefetch'];
  const onStartTyping: typeof import('@vueuse/core')['onStartTyping'];
  const onUnmounted: typeof import('vue')['onUnmounted'];
  const onUpdated: typeof import('vue')['onUpdated'];
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup'];
  const pausableWatch: typeof import('@vueuse/core')['pausableWatch'];
  const projectsStore: typeof import('./stores/projectStore')['projectsStore'];
  const provide: typeof import('vue')['provide'];
  const provideLocal: typeof import('@vueuse/core')['provideLocal'];
  const reactify: typeof import('@vueuse/core')['reactify'];
  const reactifyObject: typeof import('@vueuse/core')['reactifyObject'];
  const reactive: typeof import('vue')['reactive'];
  const reactiveComputed: typeof import('@vueuse/core')['reactiveComputed'];
  const reactiveOmit: typeof import('@vueuse/core')['reactiveOmit'];
  const reactivePick: typeof import('@vueuse/core')['reactivePick'];
  const readonly: typeof import('vue')['readonly'];
  const ref: typeof import('vue')['ref'];
  const refAutoReset: typeof import('@vueuse/core')['refAutoReset'];
  const refDebounced: typeof import('@vueuse/core')['refDebounced'];
  const refDefault: typeof import('@vueuse/core')['refDefault'];
  const refThrottled: typeof import('@vueuse/core')['refThrottled'];
  const refWithControl: typeof import('@vueuse/core')['refWithControl'];
  const requireAuth: typeof import('./composables/useAuthGuard')['requireAuth'];
  const requirePermission: typeof import('./composables/useAuthGuard')['requirePermission'];
  const requireRole: typeof import('./composables/useAuthGuard')['requireRole'];
  const resetLocale: typeof import('./stores/locales')['resetLocale'];
  const resetTheme: typeof import('./stores/theme')['resetTheme'];
  const resolveComponent: typeof import('vue')['resolveComponent'];
  const resolveRef: typeof import('@vueuse/core')['resolveRef'];
  const resolveUnref: typeof import('@vueuse/core')['resolveUnref'];
  const setActivePinia: typeof import('pinia')['setActivePinia'];
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix'];
  const shallowReactive: typeof import('vue')['shallowReactive'];
  const shallowReadonly: typeof import('vue')['shallowReadonly'];
  const shallowRef: typeof import('vue')['shallowRef'];
  const startLocaleStore: typeof import('./stores/locales')['startLocaleStore'];
  const startThemeStore: typeof import('./stores/theme')['startThemeStore'];
  const storeStart: typeof import('./stores/index')['storeStart'];
  const storeToRefs: typeof import('pinia')['storeToRefs'];
  const syncRef: typeof import('@vueuse/core')['syncRef'];
  const syncRefs: typeof import('@vueuse/core')['syncRefs'];
  const tagsStore: typeof import('./stores/tagStore')['tagsStore'];
  const templateRef: typeof import('@vueuse/core')['templateRef'];
  const throttledRef: typeof import('@vueuse/core')['throttledRef'];
  const throttledWatch: typeof import('@vueuse/core')['throttledWatch'];
  const toRaw: typeof import('vue')['toRaw'];
  const toReactive: typeof import('@vueuse/core')['toReactive'];
  const toRef: typeof import('vue')['toRef'];
  const toRefs: typeof import('vue')['toRefs'];
  const toValue: typeof import('vue')['toValue'];
  const triggerRef: typeof import('vue')['triggerRef'];
  const tryOnBeforeMount: typeof import('@vueuse/core')['tryOnBeforeMount'];
  const tryOnBeforeUnmount: typeof import('@vueuse/core')['tryOnBeforeUnmount'];
  const tryOnMounted: typeof import('@vueuse/core')['tryOnMounted'];
  const tryOnScopeDispose: typeof import('@vueuse/core')['tryOnScopeDispose'];
  const tryOnUnmounted: typeof import('@vueuse/core')['tryOnUnmounted'];
  const unref: typeof import('vue')['unref'];
  const unrefElement: typeof import('@vueuse/core')['unrefElement'];
  const until: typeof import('@vueuse/core')['until'];
  const updateLocale: typeof import('./stores/locales')['updateLocale'];
  const updateTheme: typeof import('./stores/theme')['updateTheme'];
  const useAccountActions: typeof import('./composables/useAccountActions')['useAccountActions'];
  const useActiveElement: typeof import('@vueuse/core')['useActiveElement'];
  const useAnimate: typeof import('@vueuse/core')['useAnimate'];
  const useArrayDifference: typeof import('@vueuse/core')['useArrayDifference'];
  const useArrayEvery: typeof import('@vueuse/core')['useArrayEvery'];
  const useArrayFilter: typeof import('@vueuse/core')['useArrayFilter'];
  const useArrayFind: typeof import('@vueuse/core')['useArrayFind'];
  const useArrayFindIndex: typeof import('@vueuse/core')['useArrayFindIndex'];
  const useArrayFindLast: typeof import('@vueuse/core')['useArrayFindLast'];
  const useArrayIncludes: typeof import('@vueuse/core')['useArrayIncludes'];
  const useArrayJoin: typeof import('@vueuse/core')['useArrayJoin'];
  const useArrayMap: typeof import('@vueuse/core')['useArrayMap'];
  const useArrayReduce: typeof import('@vueuse/core')['useArrayReduce'];
  const useArraySome: typeof import('@vueuse/core')['useArraySome'];
  const useArrayUnique: typeof import('@vueuse/core')['useArrayUnique'];
  const useAsyncQueue: typeof import('@vueuse/core')['useAsyncQueue'];
  const useAsyncState: typeof import('@vueuse/core')['useAsyncState'];
  const useAttrs: typeof import('vue')['useAttrs'];
  const useAuthGuard: typeof import('./composables/useAuthGuard')['useAuthGuard'];
  const useAuthPermission: typeof import('./composables/useAuthPermission')['useAuthPermission'];
  const useAuthStore: typeof import('./stores/auth')['useAuthStore'];
  const useAutoSaveSettings: typeof import('./composables/useAutoSaveSettings')['useAutoSaveSettings'];
  const useBase64: typeof import('@vueuse/core')['useBase64'];
  const useBattery: typeof import('@vueuse/core')['useBattery'];
  const useBluetooth: typeof import('@vueuse/core')['useBluetooth'];
  const useBreakpoints: typeof import('@vueuse/core')['useBreakpoints'];
  const useBroadcastChannel: typeof import('@vueuse/core')['useBroadcastChannel'];
  const useBrowserLocation: typeof import('@vueuse/core')['useBrowserLocation'];
  const useBudgetActions: typeof import('./composables/useBudgetActions')['useBudgetActions'];
  const useBudgetForm: typeof import('./composables/useBudgetForm')['useBudgetForm'];
  const useBudgetStats: typeof import('./composables/useBudgetStats')['useBudgetStats'];
  const useCached: typeof import('@vueuse/core')['useCached'];
  const useClipboard: typeof import('@vueuse/core')['useClipboard'];
  const useClipboardItems: typeof import('@vueuse/core')['useClipboardItems'];
  const useCloned: typeof import('@vueuse/core')['useCloned'];
  const useColorMode: typeof import('@vueuse/core')['useColorMode'];
  const useConfirm: typeof import('./composables/useConfirm')['useConfirm'];
  const useConfirmDialog: typeof import('@vueuse/core')['useConfirmDialog'];
  const useCountdown: typeof import('@vueuse/core')['useCountdown'];
  const useCounter: typeof import('@vueuse/core')['useCounter'];
  const useCrudActions: typeof import('./composables/useCrudActions')['useCrudActions'];
  const useCssModule: typeof import('vue')['useCssModule'];
  const useCssVar: typeof import('@vueuse/core')['useCssVar'];
  const useCssVars: typeof import('vue')['useCssVars'];
  const useCurrentElement: typeof import('@vueuse/core')['useCurrentElement'];
  const useCycleList: typeof import('@vueuse/core')['useCycleList'];
  const useDark: typeof import('@vueuse/core')['useDark'];
  const useDateFormat: typeof import('@vueuse/core')['useDateFormat'];
  const useDebounce: typeof import('@vueuse/core')['useDebounce'];
  const useDebounceFn: typeof import('@vueuse/core')['useDebounceFn'];
  const useDebouncedRefHistory: typeof import('@vueuse/core')['useDebouncedRefHistory'];
  const useDeviceMotion: typeof import('@vueuse/core')['useDeviceMotion'];
  const useDeviceOrientation: typeof import('@vueuse/core')['useDeviceOrientation'];
  const useDevicePixelRatio: typeof import('@vueuse/core')['useDevicePixelRatio'];
  const useDevicesList: typeof import('@vueuse/core')['useDevicesList'];
  const useDisplayMedia: typeof import('@vueuse/core')['useDisplayMedia'];
  const useDocumentVisibility: typeof import('@vueuse/core')['useDocumentVisibility'];
  const useDraggable: typeof import('@vueuse/core')['useDraggable'];
  const useDropZone: typeof import('@vueuse/core')['useDropZone'];
  const useElementBounding: typeof import('@vueuse/core')['useElementBounding'];
  const useElementByPoint: typeof import('@vueuse/core')['useElementByPoint'];
  const useElementHover: typeof import('@vueuse/core')['useElementHover'];
  const useElementSize: typeof import('@vueuse/core')['useElementSize'];
  const useElementVisibility: typeof import('@vueuse/core')['useElementVisibility'];
  const useEventBus: typeof import('@vueuse/core')['useEventBus'];
  const useEventListener: typeof import('@vueuse/core')['useEventListener'];
  const useEventSource: typeof import('@vueuse/core')['useEventSource'];
  const useEyeDropper: typeof import('@vueuse/core')['useEyeDropper'];
  const useFamilyBudgetActions: typeof import('./composables/useFamilyBudgetActions')['useFamilyBudgetActions'];
  const useFamilyMemberSearch: typeof import('./composables/useFamilyMemberSearch')['useFamilyMemberSearch'];
  const useFavicon: typeof import('@vueuse/core')['useFavicon'];
  const useFetch: typeof import('@vueuse/core')['useFetch'];
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog'];
  const useFileSystemAccess: typeof import('@vueuse/core')['useFileSystemAccess'];
  const useFirstLaunch: typeof import('./composables/useFirstLaunch')['useFirstLaunch'];
  const useFocus: typeof import('@vueuse/core')['useFocus'];
  const useFocusWithin: typeof import('@vueuse/core')['useFocusWithin'];
  const useFormValidation: typeof import('./composables/useFormValidation')['useFormValidation'];
  const useFps: typeof import('@vueuse/core')['useFps'];
  const useFullscreen: typeof import('@vueuse/core')['useFullscreen'];
  const useGamepad: typeof import('@vueuse/core')['useGamepad'];
  const useGeolocation: typeof import('@vueuse/core')['useGeolocation'];
  const useI18n: typeof import('vue-i18n')['useI18n'];
  const useId: typeof import('vue')['useId'];
  const useIdle: typeof import('@vueuse/core')['useIdle'];
  const useImage: typeof import('@vueuse/core')['useImage'];
  const useInfiniteScroll: typeof import('@vueuse/core')['useInfiniteScroll'];
  const useIntersectionObserver: typeof import('@vueuse/core')['useIntersectionObserver'];
  const useInterval: typeof import('@vueuse/core')['useInterval'];
  const useIntervalFn: typeof import('@vueuse/core')['useIntervalFn'];
  const useKeyModifier: typeof import('@vueuse/core')['useKeyModifier'];
  const useKeyboardShortcuts: typeof import('./composables/useKeyboardShortcuts')['useKeyboardShortcuts'];
  const useLastChanged: typeof import('@vueuse/core')['useLastChanged'];
  const useLink: typeof import('vue-router/auto')['useLink'];
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage'];
  const useLocaleStore: typeof import('./stores/locales')['useLocaleStore'];
  const useLocaleStores: typeof import('./stores/locales')['useLocaleStores'];
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys'];
  const useManualRefHistory: typeof import('@vueuse/core')['useManualRefHistory'];
  const useMediaControls: typeof import('@vueuse/core')['useMediaControls'];
  const useMediaQueriesStore: typeof import('./stores/mediaQueries')['useMediaQueriesStore'];
  const useMediaQuery: typeof import('@vueuse/core')['useMediaQuery'];
  const useMemoize: typeof import('@vueuse/core')['useMemoize'];
  const useMemory: typeof import('@vueuse/core')['useMemory'];
  const useMenuStore: typeof import('./stores/menuStore')['useMenuStore'];
  const useModel: typeof import('vue')['useModel'];
  const useModuleReminderListener: typeof import('./composables/useUnifiedReminderListener')['useModuleReminderListener'];
  const useMoneyAuth: typeof import('./composables/useMoneyAuth')['useMoneyAuth'];
  const useMoneyStats: typeof import('./composables/useMoneyStats')['useMoneyStats'];
  const useMoneyStore: typeof import('./stores/moneyStore')['useMoneyStore'];
  const useMoneyStores: typeof import('./stores/moneyStore')['useMoneyStores'];
  const useMounted: typeof import('@vueuse/core')['useMounted'];
  const useMouse: typeof import('@vueuse/core')['useMouse'];
  const useMouseInElement: typeof import('@vueuse/core')['useMouseInElement'];
  const useMousePressed: typeof import('@vueuse/core')['useMousePressed'];
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver'];
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage'];
  const useNetwork: typeof import('@vueuse/core')['useNetwork'];
  const useNotificationPermission: typeof import('./composables/useNotificationPermission')['useNotificationPermission'];
  const useNotificationSettings: typeof import('./composables/useNotificationSettings')['useNotificationSettings'];
  const useNotificationStore: typeof import('./stores/notification')['useNotificationStore'];
  const useNow: typeof import('@vueuse/core')['useNow'];
  const useObjectUrl: typeof import('@vueuse/core')['useObjectUrl'];
  const useOffsetPagination: typeof import('@vueuse/core')['useOffsetPagination'];
  const useOnline: typeof import('@vueuse/core')['useOnline'];
  const usePageLeave: typeof import('@vueuse/core')['usePageLeave'];
  const usePagination: typeof import('./composables/usePagination')['usePagination'];
  const usePaginationFilters: typeof import('./composables/usePaginationFilters')['usePaginationFilters'];
  const usePaginationMapFilters: typeof import('./composables/usePaginationFilters')['usePaginationMapFilters'];
  const useParallax: typeof import('@vueuse/core')['useParallax'];
  const useParentElement: typeof import('@vueuse/core')['useParentElement'];
  const usePerformanceObserver: typeof import('@vueuse/core')['usePerformanceObserver'];
  const usePeriodStore: typeof import('./stores/periodStore')['usePeriodStore'];
  const usePermission: typeof import('./composables/usePermission')['usePermission'];
  const usePointer: typeof import('@vueuse/core')['usePointer'];
  const usePointerLock: typeof import('@vueuse/core')['usePointerLock'];
  const usePointerSwipe: typeof import('@vueuse/core')['usePointerSwipe'];
  const usePreferredColorScheme: typeof import('@vueuse/core')['usePreferredColorScheme'];
  const usePreferredContrast: typeof import('@vueuse/core')['usePreferredContrast'];
  const usePreferredDark: typeof import('@vueuse/core')['usePreferredDark'];
  const usePreferredLanguages: typeof import('@vueuse/core')['usePreferredLanguages'];
  const usePreferredReducedMotion: typeof import('@vueuse/core')['usePreferredReducedMotion'];
  const usePreferredReducedTransparency: typeof import('@vueuse/core')['usePreferredReducedTransparency'];
  const usePrevious: typeof import('@vueuse/core')['usePrevious'];
  const useRafFn: typeof import('@vueuse/core')['useRafFn'];
  const useRefHistory: typeof import('@vueuse/core')['useRefHistory'];
  const useReminderActions: typeof import('./composables/useReminderActions')['useReminderActions'];
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver'];
  const useRoute: typeof import('vue-router')['useRoute'];
  const useRouter: typeof import('vue-router')['useRouter'];
  const useSSRWidth: typeof import('@vueuse/core')['useSSRWidth'];
  const useScreenOrientation: typeof import('@vueuse/core')['useScreenOrientation'];
  const useScreenSafeArea: typeof import('@vueuse/core')['useScreenSafeArea'];
  const useScriptTag: typeof import('@vueuse/core')['useScriptTag'];
  const useScroll: typeof import('@vueuse/core')['useScroll'];
  const useScrollLock: typeof import('@vueuse/core')['useScrollLock'];
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage'];
  const useSettingsCache: typeof import('./composables/useSettingsCache')['useSettingsCache'];
  const useShare: typeof import('@vueuse/core')['useShare'];
  const useSlots: typeof import('vue')['useSlots'];
  const useSort: typeof import('./composables/useSortable')['useSort'];
  const useSorted: typeof import('@vueuse/core')['useSorted'];
  const useSpeechRecognition: typeof import('@vueuse/core')['useSpeechRecognition'];
  const useSpeechSynthesis: typeof import('@vueuse/core')['useSpeechSynthesis'];
  const useSplitCalculator: typeof import('./composables/useSplitCalculator')['useSplitCalculator'];
  const useStepper: typeof import('@vueuse/core')['useStepper'];
  const useStorage: typeof import('@vueuse/core')['useStorage'];
  const useStorageAsync: typeof import('@vueuse/core')['useStorageAsync'];
  const useStyleTag: typeof import('@vueuse/core')['useStyleTag'];
  const useSupported: typeof import('@vueuse/core')['useSupported'];
  const useSwipe: typeof import('@vueuse/core')['useSwipe'];
  const useTabManager: typeof import('./composables/useTabManager')['useTabManager'];
  const useTagStore: typeof import('./stores/tagStore')['useTagStore'];
  const useTemplateRef: typeof import('vue')['useTemplateRef'];
  const useTemplateRefsList: typeof import('@vueuse/core')['useTemplateRefsList'];
  const useTextDirection: typeof import('@vueuse/core')['useTextDirection'];
  const useTextSelection: typeof import('@vueuse/core')['useTextSelection'];
  const useTextareaAutosize: typeof import('@vueuse/core')['useTextareaAutosize'];
  const useTheme: typeof import('./composables/useTheme')['useTheme'];
  const useThemeStore: typeof import('./stores/theme')['useThemeStore'];
  const useThrottle: typeof import('@vueuse/core')['useThrottle'];
  const useThrottleFn: typeof import('@vueuse/core')['useThrottleFn'];
  const useThrottledRefHistory: typeof import('@vueuse/core')['useThrottledRefHistory'];
  const useTimeAgo: typeof import('@vueuse/core')['useTimeAgo'];
  const useTimeAgoIntl: typeof import('@vueuse/core')['useTimeAgoIntl'];
  const useTimeout: typeof import('@vueuse/core')['useTimeout'];
  const useTimeoutFn: typeof import('@vueuse/core')['useTimeoutFn'];
  const useTimeoutPoll: typeof import('@vueuse/core')['useTimeoutPoll'];
  const useTimestamp: typeof import('@vueuse/core')['useTimestamp'];
  const useTitle: typeof import('@vueuse/core')['useTitle'];
  const useToNumber: typeof import('@vueuse/core')['useToNumber'];
  const useToString: typeof import('@vueuse/core')['useToString'];
  const useTodoStore: typeof import('./stores/todoStore')['useTodoStore'];
  const useToggle: typeof import('@vueuse/core')['useToggle'];
  const useTransactionActions: typeof import('./composables/useTransactionActions')['useTransactionActions'];
  const useTransition: typeof import('@vueuse/core')['useTransition'];
  const useTransitionsStore: typeof import('./stores/transition')['useTransitionsStore'];
  const useTray: typeof import('./composables/useTray')['useTray'];
  const useUnifiedReminderListener: typeof import('./composables/useUnifiedReminderListener')['useUnifiedReminderListener'];
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams'];
  const useUserMedia: typeof import('@vueuse/core')['useUserMedia'];
  const useUserSearch: typeof import('./composables/useUserSearch')['useUserSearch'];
  const useVModel: typeof import('@vueuse/core')['useVModel'];
  const useVModels: typeof import('@vueuse/core')['useVModels'];
  const useVibrate: typeof import('@vueuse/core')['useVibrate'];
  const useVirtualList: typeof import('@vueuse/core')['useVirtualList'];
  const useWakeLock: typeof import('@vueuse/core')['useWakeLock'];
  const useWebNotification: typeof import('@vueuse/core')['useWebNotification'];
  const useWebSocket: typeof import('@vueuse/core')['useWebSocket'];
  const useWebWorker: typeof import('@vueuse/core')['useWebWorker'];
  const useWebWorkerFn: typeof import('@vueuse/core')['useWebWorkerFn'];
  const useWindowFocus: typeof import('@vueuse/core')['useWindowFocus'];
  const useWindowScroll: typeof import('@vueuse/core')['useWindowScroll'];
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize'];
  const watch: typeof import('vue')['watch'];
  const watchArray: typeof import('@vueuse/core')['watchArray'];
  const watchAtMost: typeof import('@vueuse/core')['watchAtMost'];
  const watchDebounced: typeof import('@vueuse/core')['watchDebounced'];
  const watchDeep: typeof import('@vueuse/core')['watchDeep'];
  const watchEffect: typeof import('vue')['watchEffect'];
  const watchIgnorable: typeof import('@vueuse/core')['watchIgnorable'];
  const watchImmediate: typeof import('@vueuse/core')['watchImmediate'];
  const watchOnce: typeof import('@vueuse/core')['watchOnce'];
  const watchPausable: typeof import('@vueuse/core')['watchPausable'];
  const watchPostEffect: typeof import('vue')['watchPostEffect'];
  const watchSyncEffect: typeof import('vue')['watchSyncEffect'];
  const watchThrottled: typeof import('@vueuse/core')['watchThrottled'];
  const watchTriggerable: typeof import('@vueuse/core')['watchTriggerable'];
  const watchWithFilter: typeof import('@vueuse/core')['watchWithFilter'];
  const whenever: typeof import('@vueuse/core')['whenever'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    Slot,
    Slots,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef,
  } from 'vue';
  import('vue');
  // @ts-ignore
  export type { AuthUser, TokenResponse, User } from './stores/auth';
  import('./stores/auth');
  // @ts-ignore
  export type { SupportedLocale } from './stores/locales';
  import('./stores/locales');
  // @ts-ignore
  export type { MediaBreakpoints } from './stores/mediaQueries';
  import('./stores/mediaQueries');
  // @ts-ignore
  export type { HealthStoreErrorCode, HealthDbError } from './stores/periodStore';
  import('./stores/periodStore');
  // @ts-ignore
  export type { ThemeMode, ThemeOption } from './stores/theme';
  import('./stores/theme');
  // @ts-ignore
  export type { TodoStoreErrorCode } from './stores/todoStore';
  import('./stores/todoStore');
  // @ts-ignore
  export type { AuthGuardOptions } from './composables/useAuthGuard';
  import('./composables/useAuthGuard');
  // @ts-ignore
  export type { SettingField, AutoSaveSettingsConfig } from './composables/useAutoSaveSettings';
  import('./composables/useAutoSaveSettings');
  // @ts-ignore
  export type { BudgetStatsState, BudgetStatsFilters } from './composables/useBudgetStats';
  import('./composables/useBudgetStats');
  // @ts-ignore
  export type {
    CrudActionErrorCode,
    CrudStore,
    BatchOperationResult,
    OptimisticUpdateConfig,
    CrudActionsOptions,
  } from './composables/useCrudActions';
  import('./composables/useCrudActions');
  // @ts-ignore
  export type { FamilyMember } from './composables/useFamilyMemberSearch';
  import('./composables/useFamilyMemberSearch');
  // @ts-ignore
  export type { FormValidationOptions } from './composables/useFormValidation';
  import('./composables/useFormValidation');
  // @ts-ignore
  export type { KeyboardShortcut } from './composables/useKeyboardShortcuts';
  import('./composables/useKeyboardShortcuts');
  // @ts-ignore
  export type { PaginationOptions, PaginationReturn } from './composables/usePagination';
  import('./composables/usePagination');
  // @ts-ignore
  export type { SettingsConfig } from './composables/useSettingsCache';
  import('./composables/useSettingsCache');
  // @ts-ignore
  export type { SplitType, SplitResult } from './composables/useSplitCalculator';
  import('./composables/useSplitCalculator');
  // @ts-ignore
  export type { TabType } from './composables/useTabManager';
  import('./composables/useTabManager');
  // @ts-ignore
  export type { ReminderEventHandlers } from './composables/useUnifiedReminderListener';
  import('./composables/useUnifiedReminderListener');
}

// for vue template auto import
import { UnwrapRef } from 'vue';
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly CrudActionErrorCode: UnwrapRef<
      typeof import('./composables/useCrudActions')['CrudActionErrorCode']
    >;
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>;
    readonly HealthDbError: UnwrapRef<typeof import('./stores/periodStore')['HealthDbError']>;
    readonly HealthStoreErrorCode: UnwrapRef<
      typeof import('./stores/periodStore')['HealthStoreErrorCode']
    >;
    readonly MEDIA_BREAKPOINTS: UnwrapRef<
      typeof import('./stores/mediaQueries')['MEDIA_BREAKPOINTS']
    >;
    readonly SplitType: UnwrapRef<typeof import('./composables/useSplitCalculator')['SplitType']>;
    readonly TodoStoreErrorCode: UnwrapRef<
      typeof import('./stores/todoStore')['TodoStoreErrorCode']
    >;
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>;
    readonly asyncComputed: UnwrapRef<typeof import('@vueuse/core')['asyncComputed']>;
    readonly autoResetRef: UnwrapRef<typeof import('@vueuse/core')['autoResetRef']>;
    readonly clearAllSettingsCache: UnwrapRef<
      typeof import('./composables/useSettingsCache')['clearAllSettingsCache']
    >;
    readonly compareTodos: UnwrapRef<typeof import('./stores/todoStore')['compareTodos']>;
    readonly computed: UnwrapRef<typeof import('vue')['computed']>;
    readonly computedAsync: UnwrapRef<typeof import('@vueuse/core')['computedAsync']>;
    readonly computedEager: UnwrapRef<typeof import('@vueuse/core')['computedEager']>;
    readonly computedInject: UnwrapRef<typeof import('@vueuse/core')['computedInject']>;
    readonly computedWithControl: UnwrapRef<typeof import('@vueuse/core')['computedWithControl']>;
    readonly controlledComputed: UnwrapRef<typeof import('@vueuse/core')['controlledComputed']>;
    readonly controlledRef: UnwrapRef<typeof import('@vueuse/core')['controlledRef']>;
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>;
    readonly createDatabaseSetting: UnwrapRef<
      typeof import('./composables/useAutoSaveSettings')['createDatabaseSetting']
    >;
    readonly createEventHook: UnwrapRef<typeof import('@vueuse/core')['createEventHook']>;
    readonly createFieldValidator: UnwrapRef<
      typeof import('./composables/useFormValidation')['createFieldValidator']
    >;
    readonly createGlobalState: UnwrapRef<typeof import('@vueuse/core')['createGlobalState']>;
    readonly createInjectionState: UnwrapRef<typeof import('@vueuse/core')['createInjectionState']>;
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>;
    readonly createReactiveFn: UnwrapRef<typeof import('@vueuse/core')['createReactiveFn']>;
    readonly createRef: UnwrapRef<typeof import('@vueuse/core')['createRef']>;
    readonly createReusableTemplate: UnwrapRef<
      typeof import('@vueuse/core')['createReusableTemplate']
    >;
    readonly createSharedComposable: UnwrapRef<
      typeof import('@vueuse/core')['createSharedComposable']
    >;
    readonly createSimpleSetting: UnwrapRef<
      typeof import('./composables/useAutoSaveSettings')['createSimpleSetting']
    >;
    readonly createTauriSetting: UnwrapRef<
      typeof import('./composables/useAutoSaveSettings')['createTauriSetting']
    >;
    readonly createTemplatePromise: UnwrapRef<
      typeof import('@vueuse/core')['createTemplatePromise']
    >;
    readonly createUnrefFn: UnwrapRef<typeof import('@vueuse/core')['createUnrefFn']>;
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>;
    readonly debouncedRef: UnwrapRef<typeof import('@vueuse/core')['debouncedRef']>;
    readonly debouncedWatch: UnwrapRef<typeof import('@vueuse/core')['debouncedWatch']>;
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>;
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>;
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>;
    readonly eagerComputed: UnwrapRef<typeof import('@vueuse/core')['eagerComputed']>;
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>;
    readonly extendRef: UnwrapRef<typeof import('@vueuse/core')['extendRef']>;
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>;
    readonly getBrowserLocale: UnwrapRef<typeof import('./stores/locales')['getBrowserLocale']>;
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>;
    readonly getCurrentLocale: UnwrapRef<typeof import('./stores/locales')['getCurrentLocale']>;
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>;
    readonly getCurrentTheme: UnwrapRef<typeof import('./stores/theme')['getCurrentTheme']>;
    readonly getCurrentUser: UnwrapRef<typeof import('./stores/auth')['getCurrentUser']>;
    readonly getLocaleFlag: UnwrapRef<typeof import('./stores/locales')['getLocaleFlag']>;
    readonly getLocaleName: UnwrapRef<typeof import('./stores/locales')['getLocaleName']>;
    readonly getSettingsCacheManager: UnwrapRef<
      typeof import('./composables/useSettingsCache')['getSettingsCacheManager']
    >;
    readonly getSupportedLocales: UnwrapRef<
      typeof import('./stores/locales')['getSupportedLocales']
    >;
    readonly h: UnwrapRef<typeof import('vue')['h']>;
    readonly ignorableWatch: UnwrapRef<typeof import('@vueuse/core')['ignorableWatch']>;
    readonly inject: UnwrapRef<typeof import('vue')['inject']>;
    readonly injectLocal: UnwrapRef<typeof import('@vueuse/core')['injectLocal']>;
    readonly isAuthenticated: UnwrapRef<typeof import('./stores/auth')['isAuthenticated']>;
    readonly isDefined: UnwrapRef<typeof import('@vueuse/core')['isDefined']>;
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>;
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>;
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>;
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>;
    readonly isSupportedLocale: UnwrapRef<typeof import('./stores/locales')['isSupportedLocale']>;
    readonly loginUser: UnwrapRef<typeof import('./stores/auth')['loginUser']>;
    readonly logoutUser: UnwrapRef<typeof import('./stores/auth')['logoutUser']>;
    readonly makeDestructurable: UnwrapRef<typeof import('@vueuse/core')['makeDestructurable']>;
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>;
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>;
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>;
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>;
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>;
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>;
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>;
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>;
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>;
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>;
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>;
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>;
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>;
    readonly onClickOutside: UnwrapRef<typeof import('@vueuse/core')['onClickOutside']>;
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>;
    readonly onElementRemoval: UnwrapRef<typeof import('@vueuse/core')['onElementRemoval']>;
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>;
    readonly onKeyStroke: UnwrapRef<typeof import('@vueuse/core')['onKeyStroke']>;
    readonly onLongPress: UnwrapRef<typeof import('@vueuse/core')['onLongPress']>;
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>;
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>;
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>;
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>;
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>;
    readonly onStartTyping: UnwrapRef<typeof import('@vueuse/core')['onStartTyping']>;
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>;
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>;
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>;
    readonly pausableWatch: UnwrapRef<typeof import('@vueuse/core')['pausableWatch']>;
    readonly projectsStore: UnwrapRef<typeof import('./stores/projectStore')['projectsStore']>;
    readonly provide: UnwrapRef<typeof import('vue')['provide']>;
    readonly provideLocal: UnwrapRef<typeof import('@vueuse/core')['provideLocal']>;
    readonly reactify: UnwrapRef<typeof import('@vueuse/core')['reactify']>;
    readonly reactifyObject: UnwrapRef<typeof import('@vueuse/core')['reactifyObject']>;
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>;
    readonly reactiveComputed: UnwrapRef<typeof import('@vueuse/core')['reactiveComputed']>;
    readonly reactiveOmit: UnwrapRef<typeof import('@vueuse/core')['reactiveOmit']>;
    readonly reactivePick: UnwrapRef<typeof import('@vueuse/core')['reactivePick']>;
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>;
    readonly ref: UnwrapRef<typeof import('vue')['ref']>;
    readonly refAutoReset: UnwrapRef<typeof import('@vueuse/core')['refAutoReset']>;
    readonly refDebounced: UnwrapRef<typeof import('@vueuse/core')['refDebounced']>;
    readonly refDefault: UnwrapRef<typeof import('@vueuse/core')['refDefault']>;
    readonly refThrottled: UnwrapRef<typeof import('@vueuse/core')['refThrottled']>;
    readonly refWithControl: UnwrapRef<typeof import('@vueuse/core')['refWithControl']>;
    readonly requireAuth: UnwrapRef<typeof import('./composables/useAuthGuard')['requireAuth']>;
    readonly requirePermission: UnwrapRef<
      typeof import('./composables/useAuthGuard')['requirePermission']
    >;
    readonly requireRole: UnwrapRef<typeof import('./composables/useAuthGuard')['requireRole']>;
    readonly resetLocale: UnwrapRef<typeof import('./stores/locales')['resetLocale']>;
    readonly resetTheme: UnwrapRef<typeof import('./stores/theme')['resetTheme']>;
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>;
    readonly resolveRef: UnwrapRef<typeof import('@vueuse/core')['resolveRef']>;
    readonly resolveUnref: UnwrapRef<typeof import('@vueuse/core')['resolveUnref']>;
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>;
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>;
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>;
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>;
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>;
    readonly startLocaleStore: UnwrapRef<typeof import('./stores/locales')['startLocaleStore']>;
    readonly startThemeStore: UnwrapRef<typeof import('./stores/theme')['startThemeStore']>;
    readonly storeStart: UnwrapRef<typeof import('./stores/index')['storeStart']>;
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>;
    readonly syncRef: UnwrapRef<typeof import('@vueuse/core')['syncRef']>;
    readonly syncRefs: UnwrapRef<typeof import('@vueuse/core')['syncRefs']>;
    readonly tagsStore: UnwrapRef<typeof import('./stores/tagStore')['tagsStore']>;
    readonly templateRef: UnwrapRef<typeof import('@vueuse/core')['templateRef']>;
    readonly throttledRef: UnwrapRef<typeof import('@vueuse/core')['throttledRef']>;
    readonly throttledWatch: UnwrapRef<typeof import('@vueuse/core')['throttledWatch']>;
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>;
    readonly toReactive: UnwrapRef<typeof import('@vueuse/core')['toReactive']>;
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>;
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>;
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>;
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>;
    readonly tryOnBeforeMount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeMount']>;
    readonly tryOnBeforeUnmount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeUnmount']>;
    readonly tryOnMounted: UnwrapRef<typeof import('@vueuse/core')['tryOnMounted']>;
    readonly tryOnScopeDispose: UnwrapRef<typeof import('@vueuse/core')['tryOnScopeDispose']>;
    readonly tryOnUnmounted: UnwrapRef<typeof import('@vueuse/core')['tryOnUnmounted']>;
    readonly unref: UnwrapRef<typeof import('vue')['unref']>;
    readonly unrefElement: UnwrapRef<typeof import('@vueuse/core')['unrefElement']>;
    readonly until: UnwrapRef<typeof import('@vueuse/core')['until']>;
    readonly updateLocale: UnwrapRef<typeof import('./stores/locales')['updateLocale']>;
    readonly updateTheme: UnwrapRef<typeof import('./stores/theme')['updateTheme']>;
    readonly useAccountActions: UnwrapRef<
      typeof import('./composables/useAccountActions')['useAccountActions']
    >;
    readonly useActiveElement: UnwrapRef<typeof import('@vueuse/core')['useActiveElement']>;
    readonly useAnimate: UnwrapRef<typeof import('@vueuse/core')['useAnimate']>;
    readonly useArrayDifference: UnwrapRef<typeof import('@vueuse/core')['useArrayDifference']>;
    readonly useArrayEvery: UnwrapRef<typeof import('@vueuse/core')['useArrayEvery']>;
    readonly useArrayFilter: UnwrapRef<typeof import('@vueuse/core')['useArrayFilter']>;
    readonly useArrayFind: UnwrapRef<typeof import('@vueuse/core')['useArrayFind']>;
    readonly useArrayFindIndex: UnwrapRef<typeof import('@vueuse/core')['useArrayFindIndex']>;
    readonly useArrayFindLast: UnwrapRef<typeof import('@vueuse/core')['useArrayFindLast']>;
    readonly useArrayIncludes: UnwrapRef<typeof import('@vueuse/core')['useArrayIncludes']>;
    readonly useArrayJoin: UnwrapRef<typeof import('@vueuse/core')['useArrayJoin']>;
    readonly useArrayMap: UnwrapRef<typeof import('@vueuse/core')['useArrayMap']>;
    readonly useArrayReduce: UnwrapRef<typeof import('@vueuse/core')['useArrayReduce']>;
    readonly useArraySome: UnwrapRef<typeof import('@vueuse/core')['useArraySome']>;
    readonly useArrayUnique: UnwrapRef<typeof import('@vueuse/core')['useArrayUnique']>;
    readonly useAsyncQueue: UnwrapRef<typeof import('@vueuse/core')['useAsyncQueue']>;
    readonly useAsyncState: UnwrapRef<typeof import('@vueuse/core')['useAsyncState']>;
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>;
    readonly useAuthGuard: UnwrapRef<typeof import('./composables/useAuthGuard')['useAuthGuard']>;
    readonly useAuthPermission: UnwrapRef<
      typeof import('./composables/useAuthPermission')['useAuthPermission']
    >;
    readonly useAuthStore: UnwrapRef<typeof import('./stores/auth')['useAuthStore']>;
    readonly useAutoSaveSettings: UnwrapRef<
      typeof import('./composables/useAutoSaveSettings')['useAutoSaveSettings']
    >;
    readonly useBase64: UnwrapRef<typeof import('@vueuse/core')['useBase64']>;
    readonly useBattery: UnwrapRef<typeof import('@vueuse/core')['useBattery']>;
    readonly useBluetooth: UnwrapRef<typeof import('@vueuse/core')['useBluetooth']>;
    readonly useBreakpoints: UnwrapRef<typeof import('@vueuse/core')['useBreakpoints']>;
    readonly useBroadcastChannel: UnwrapRef<typeof import('@vueuse/core')['useBroadcastChannel']>;
    readonly useBrowserLocation: UnwrapRef<typeof import('@vueuse/core')['useBrowserLocation']>;
    readonly useBudgetActions: UnwrapRef<
      typeof import('./composables/useBudgetActions')['useBudgetActions']
    >;
    readonly useBudgetForm: UnwrapRef<
      typeof import('./composables/useBudgetForm')['useBudgetForm']
    >;
    readonly useBudgetStats: UnwrapRef<
      typeof import('./composables/useBudgetStats')['useBudgetStats']
    >;
    readonly useCached: UnwrapRef<typeof import('@vueuse/core')['useCached']>;
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>;
    readonly useClipboardItems: UnwrapRef<typeof import('@vueuse/core')['useClipboardItems']>;
    readonly useCloned: UnwrapRef<typeof import('@vueuse/core')['useCloned']>;
    readonly useColorMode: UnwrapRef<typeof import('@vueuse/core')['useColorMode']>;
    readonly useConfirm: UnwrapRef<typeof import('./composables/useConfirm')['useConfirm']>;
    readonly useConfirmDialog: UnwrapRef<typeof import('@vueuse/core')['useConfirmDialog']>;
    readonly useCountdown: UnwrapRef<typeof import('@vueuse/core')['useCountdown']>;
    readonly useCounter: UnwrapRef<typeof import('@vueuse/core')['useCounter']>;
    readonly useCrudActions: UnwrapRef<
      typeof import('./composables/useCrudActions')['useCrudActions']
    >;
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>;
    readonly useCssVar: UnwrapRef<typeof import('@vueuse/core')['useCssVar']>;
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>;
    readonly useCurrentElement: UnwrapRef<typeof import('@vueuse/core')['useCurrentElement']>;
    readonly useCycleList: UnwrapRef<typeof import('@vueuse/core')['useCycleList']>;
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>;
    readonly useDateFormat: UnwrapRef<typeof import('@vueuse/core')['useDateFormat']>;
    readonly useDebounce: UnwrapRef<typeof import('@vueuse/core')['useDebounce']>;
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>;
    readonly useDebouncedRefHistory: UnwrapRef<
      typeof import('@vueuse/core')['useDebouncedRefHistory']
    >;
    readonly useDeviceMotion: UnwrapRef<typeof import('@vueuse/core')['useDeviceMotion']>;
    readonly useDeviceOrientation: UnwrapRef<typeof import('@vueuse/core')['useDeviceOrientation']>;
    readonly useDevicePixelRatio: UnwrapRef<typeof import('@vueuse/core')['useDevicePixelRatio']>;
    readonly useDevicesList: UnwrapRef<typeof import('@vueuse/core')['useDevicesList']>;
    readonly useDisplayMedia: UnwrapRef<typeof import('@vueuse/core')['useDisplayMedia']>;
    readonly useDocumentVisibility: UnwrapRef<
      typeof import('@vueuse/core')['useDocumentVisibility']
    >;
    readonly useDraggable: UnwrapRef<typeof import('@vueuse/core')['useDraggable']>;
    readonly useDropZone: UnwrapRef<typeof import('@vueuse/core')['useDropZone']>;
    readonly useElementBounding: UnwrapRef<typeof import('@vueuse/core')['useElementBounding']>;
    readonly useElementByPoint: UnwrapRef<typeof import('@vueuse/core')['useElementByPoint']>;
    readonly useElementHover: UnwrapRef<typeof import('@vueuse/core')['useElementHover']>;
    readonly useElementSize: UnwrapRef<typeof import('@vueuse/core')['useElementSize']>;
    readonly useElementVisibility: UnwrapRef<typeof import('@vueuse/core')['useElementVisibility']>;
    readonly useEventBus: UnwrapRef<typeof import('@vueuse/core')['useEventBus']>;
    readonly useEventListener: UnwrapRef<typeof import('@vueuse/core')['useEventListener']>;
    readonly useEventSource: UnwrapRef<typeof import('@vueuse/core')['useEventSource']>;
    readonly useEyeDropper: UnwrapRef<typeof import('@vueuse/core')['useEyeDropper']>;
    readonly useFamilyBudgetActions: UnwrapRef<
      typeof import('./composables/useFamilyBudgetActions')['useFamilyBudgetActions']
    >;
    readonly useFamilyMemberSearch: UnwrapRef<
      typeof import('./composables/useFamilyMemberSearch')['useFamilyMemberSearch']
    >;
    readonly useFavicon: UnwrapRef<typeof import('@vueuse/core')['useFavicon']>;
    readonly useFetch: UnwrapRef<typeof import('@vueuse/core')['useFetch']>;
    readonly useFileDialog: UnwrapRef<typeof import('@vueuse/core')['useFileDialog']>;
    readonly useFileSystemAccess: UnwrapRef<typeof import('@vueuse/core')['useFileSystemAccess']>;
    readonly useFirstLaunch: UnwrapRef<
      typeof import('./composables/useFirstLaunch')['useFirstLaunch']
    >;
    readonly useFocus: UnwrapRef<typeof import('@vueuse/core')['useFocus']>;
    readonly useFocusWithin: UnwrapRef<typeof import('@vueuse/core')['useFocusWithin']>;
    readonly useFormValidation: UnwrapRef<
      typeof import('./composables/useFormValidation')['useFormValidation']
    >;
    readonly useFps: UnwrapRef<typeof import('@vueuse/core')['useFps']>;
    readonly useFullscreen: UnwrapRef<typeof import('@vueuse/core')['useFullscreen']>;
    readonly useGamepad: UnwrapRef<typeof import('@vueuse/core')['useGamepad']>;
    readonly useGeolocation: UnwrapRef<typeof import('@vueuse/core')['useGeolocation']>;
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>;
    readonly useId: UnwrapRef<typeof import('vue')['useId']>;
    readonly useIdle: UnwrapRef<typeof import('@vueuse/core')['useIdle']>;
    readonly useImage: UnwrapRef<typeof import('@vueuse/core')['useImage']>;
    readonly useInfiniteScroll: UnwrapRef<typeof import('@vueuse/core')['useInfiniteScroll']>;
    readonly useIntersectionObserver: UnwrapRef<
      typeof import('@vueuse/core')['useIntersectionObserver']
    >;
    readonly useInterval: UnwrapRef<typeof import('@vueuse/core')['useInterval']>;
    readonly useIntervalFn: UnwrapRef<typeof import('@vueuse/core')['useIntervalFn']>;
    readonly useKeyModifier: UnwrapRef<typeof import('@vueuse/core')['useKeyModifier']>;
    readonly useKeyboardShortcuts: UnwrapRef<
      typeof import('./composables/useKeyboardShortcuts')['useKeyboardShortcuts']
    >;
    readonly useLastChanged: UnwrapRef<typeof import('@vueuse/core')['useLastChanged']>;
    readonly useLink: UnwrapRef<typeof import('vue-router/auto')['useLink']>;
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>;
    readonly useLocaleStore: UnwrapRef<typeof import('./stores/locales')['useLocaleStore']>;
    readonly useLocaleStores: UnwrapRef<typeof import('./stores/locales')['useLocaleStores']>;
    readonly useMagicKeys: UnwrapRef<typeof import('@vueuse/core')['useMagicKeys']>;
    readonly useManualRefHistory: UnwrapRef<typeof import('@vueuse/core')['useManualRefHistory']>;
    readonly useMediaControls: UnwrapRef<typeof import('@vueuse/core')['useMediaControls']>;
    readonly useMediaQueriesStore: UnwrapRef<
      typeof import('./stores/mediaQueries')['useMediaQueriesStore']
    >;
    readonly useMediaQuery: UnwrapRef<typeof import('@vueuse/core')['useMediaQuery']>;
    readonly useMemoize: UnwrapRef<typeof import('@vueuse/core')['useMemoize']>;
    readonly useMemory: UnwrapRef<typeof import('@vueuse/core')['useMemory']>;
    readonly useMenuStore: UnwrapRef<typeof import('./stores/menuStore')['useMenuStore']>;
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>;
    readonly useModuleReminderListener: UnwrapRef<
      typeof import('./composables/useUnifiedReminderListener')['useModuleReminderListener']
    >;
    readonly useMoneyAuth: UnwrapRef<typeof import('./composables/useMoneyAuth')['useMoneyAuth']>;
    readonly useMoneyStats: UnwrapRef<
      typeof import('./composables/useMoneyStats')['useMoneyStats']
    >;
    readonly useMounted: UnwrapRef<typeof import('@vueuse/core')['useMounted']>;
    readonly useMouse: UnwrapRef<typeof import('@vueuse/core')['useMouse']>;
    readonly useMouseInElement: UnwrapRef<typeof import('@vueuse/core')['useMouseInElement']>;
    readonly useMousePressed: UnwrapRef<typeof import('@vueuse/core')['useMousePressed']>;
    readonly useMutationObserver: UnwrapRef<typeof import('@vueuse/core')['useMutationObserver']>;
    readonly useNavigatorLanguage: UnwrapRef<typeof import('@vueuse/core')['useNavigatorLanguage']>;
    readonly useNetwork: UnwrapRef<typeof import('@vueuse/core')['useNetwork']>;
    readonly useNotificationPermission: UnwrapRef<
      typeof import('./composables/useNotificationPermission')['useNotificationPermission']
    >;
    readonly useNotificationSettings: UnwrapRef<
      typeof import('./composables/useNotificationSettings')['useNotificationSettings']
    >;
    readonly useNotificationStore: UnwrapRef<
      typeof import('./stores/notification')['useNotificationStore']
    >;
    readonly useNow: UnwrapRef<typeof import('@vueuse/core')['useNow']>;
    readonly useObjectUrl: UnwrapRef<typeof import('@vueuse/core')['useObjectUrl']>;
    readonly useOffsetPagination: UnwrapRef<typeof import('@vueuse/core')['useOffsetPagination']>;
    readonly useOnline: UnwrapRef<typeof import('@vueuse/core')['useOnline']>;
    readonly usePageLeave: UnwrapRef<typeof import('@vueuse/core')['usePageLeave']>;
    readonly usePagination: UnwrapRef<
      typeof import('./composables/usePagination')['usePagination']
    >;
    readonly usePaginationFilters: UnwrapRef<
      typeof import('./composables/usePaginationFilters')['usePaginationFilters']
    >;
    readonly usePaginationMapFilters: UnwrapRef<
      typeof import('./composables/usePaginationFilters')['usePaginationMapFilters']
    >;
    readonly useParallax: UnwrapRef<typeof import('@vueuse/core')['useParallax']>;
    readonly useParentElement: UnwrapRef<typeof import('@vueuse/core')['useParentElement']>;
    readonly usePerformanceObserver: UnwrapRef<
      typeof import('@vueuse/core')['usePerformanceObserver']
    >;
    readonly usePeriodStore: UnwrapRef<typeof import('./stores/periodStore')['usePeriodStore']>;
    readonly usePermission: UnwrapRef<
      typeof import('./composables/usePermission')['usePermission']
    >;
    readonly usePointer: UnwrapRef<typeof import('@vueuse/core')['usePointer']>;
    readonly usePointerLock: UnwrapRef<typeof import('@vueuse/core')['usePointerLock']>;
    readonly usePointerSwipe: UnwrapRef<typeof import('@vueuse/core')['usePointerSwipe']>;
    readonly usePreferredColorScheme: UnwrapRef<
      typeof import('@vueuse/core')['usePreferredColorScheme']
    >;
    readonly usePreferredContrast: UnwrapRef<typeof import('@vueuse/core')['usePreferredContrast']>;
    readonly usePreferredDark: UnwrapRef<typeof import('@vueuse/core')['usePreferredDark']>;
    readonly usePreferredLanguages: UnwrapRef<
      typeof import('@vueuse/core')['usePreferredLanguages']
    >;
    readonly usePreferredReducedMotion: UnwrapRef<
      typeof import('@vueuse/core')['usePreferredReducedMotion']
    >;
    readonly usePreferredReducedTransparency: UnwrapRef<
      typeof import('@vueuse/core')['usePreferredReducedTransparency']
    >;
    readonly usePrevious: UnwrapRef<typeof import('@vueuse/core')['usePrevious']>;
    readonly useRafFn: UnwrapRef<typeof import('@vueuse/core')['useRafFn']>;
    readonly useRefHistory: UnwrapRef<typeof import('@vueuse/core')['useRefHistory']>;
    readonly useReminderActions: UnwrapRef<
      typeof import('./composables/useReminderActions')['useReminderActions']
    >;
    readonly useResizeObserver: UnwrapRef<typeof import('@vueuse/core')['useResizeObserver']>;
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>;
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>;
    readonly useSSRWidth: UnwrapRef<typeof import('@vueuse/core')['useSSRWidth']>;
    readonly useScreenOrientation: UnwrapRef<typeof import('@vueuse/core')['useScreenOrientation']>;
    readonly useScreenSafeArea: UnwrapRef<typeof import('@vueuse/core')['useScreenSafeArea']>;
    readonly useScriptTag: UnwrapRef<typeof import('@vueuse/core')['useScriptTag']>;
    readonly useScroll: UnwrapRef<typeof import('@vueuse/core')['useScroll']>;
    readonly useScrollLock: UnwrapRef<typeof import('@vueuse/core')['useScrollLock']>;
    readonly useSessionStorage: UnwrapRef<typeof import('@vueuse/core')['useSessionStorage']>;
    readonly useSettingsCache: UnwrapRef<
      typeof import('./composables/useSettingsCache')['useSettingsCache']
    >;
    readonly useShare: UnwrapRef<typeof import('@vueuse/core')['useShare']>;
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>;
    readonly useSort: UnwrapRef<typeof import('./composables/useSortable')['useSort']>;
    readonly useSorted: UnwrapRef<typeof import('@vueuse/core')['useSorted']>;
    readonly useSpeechRecognition: UnwrapRef<typeof import('@vueuse/core')['useSpeechRecognition']>;
    readonly useSpeechSynthesis: UnwrapRef<typeof import('@vueuse/core')['useSpeechSynthesis']>;
    readonly useSplitCalculator: UnwrapRef<
      typeof import('./composables/useSplitCalculator')['useSplitCalculator']
    >;
    readonly useStepper: UnwrapRef<typeof import('@vueuse/core')['useStepper']>;
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>;
    readonly useStorageAsync: UnwrapRef<typeof import('@vueuse/core')['useStorageAsync']>;
    readonly useStyleTag: UnwrapRef<typeof import('@vueuse/core')['useStyleTag']>;
    readonly useSupported: UnwrapRef<typeof import('@vueuse/core')['useSupported']>;
    readonly useSwipe: UnwrapRef<typeof import('@vueuse/core')['useSwipe']>;
    readonly useTabManager: UnwrapRef<
      typeof import('./composables/useTabManager')['useTabManager']
    >;
    readonly useTagStore: UnwrapRef<typeof import('./stores/tagStore')['useTagStore']>;
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>;
    readonly useTemplateRefsList: UnwrapRef<typeof import('@vueuse/core')['useTemplateRefsList']>;
    readonly useTextDirection: UnwrapRef<typeof import('@vueuse/core')['useTextDirection']>;
    readonly useTextSelection: UnwrapRef<typeof import('@vueuse/core')['useTextSelection']>;
    readonly useTextareaAutosize: UnwrapRef<typeof import('@vueuse/core')['useTextareaAutosize']>;
    readonly useTheme: UnwrapRef<typeof import('./composables/useTheme')['useTheme']>;
    readonly useThemeStore: UnwrapRef<typeof import('./stores/theme')['useThemeStore']>;
    readonly useThrottle: UnwrapRef<typeof import('@vueuse/core')['useThrottle']>;
    readonly useThrottleFn: UnwrapRef<typeof import('@vueuse/core')['useThrottleFn']>;
    readonly useThrottledRefHistory: UnwrapRef<
      typeof import('@vueuse/core')['useThrottledRefHistory']
    >;
    readonly useTimeAgo: UnwrapRef<typeof import('@vueuse/core')['useTimeAgo']>;
    readonly useTimeAgoIntl: UnwrapRef<typeof import('@vueuse/core')['useTimeAgoIntl']>;
    readonly useTimeout: UnwrapRef<typeof import('@vueuse/core')['useTimeout']>;
    readonly useTimeoutFn: UnwrapRef<typeof import('@vueuse/core')['useTimeoutFn']>;
    readonly useTimeoutPoll: UnwrapRef<typeof import('@vueuse/core')['useTimeoutPoll']>;
    readonly useTimestamp: UnwrapRef<typeof import('@vueuse/core')['useTimestamp']>;
    readonly useTitle: UnwrapRef<typeof import('@vueuse/core')['useTitle']>;
    readonly useToNumber: UnwrapRef<typeof import('@vueuse/core')['useToNumber']>;
    readonly useToString: UnwrapRef<typeof import('@vueuse/core')['useToString']>;
    readonly useTodoStore: UnwrapRef<typeof import('./stores/todoStore')['useTodoStore']>;
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>;
    readonly useTransactionActions: UnwrapRef<
      typeof import('./composables/useTransactionActions')['useTransactionActions']
    >;
    readonly useTransition: UnwrapRef<typeof import('@vueuse/core')['useTransition']>;
    readonly useTransitionsStore: UnwrapRef<
      typeof import('./stores/transition')['useTransitionsStore']
    >;
    readonly useTray: UnwrapRef<typeof import('./composables/useTray')['useTray']>;
    readonly useUnifiedReminderListener: UnwrapRef<
      typeof import('./composables/useUnifiedReminderListener')['useUnifiedReminderListener']
    >;
    readonly useUrlSearchParams: UnwrapRef<typeof import('@vueuse/core')['useUrlSearchParams']>;
    readonly useUserMedia: UnwrapRef<typeof import('@vueuse/core')['useUserMedia']>;
    readonly useUserSearch: UnwrapRef<
      typeof import('./composables/useUserSearch')['useUserSearch']
    >;
    readonly useVModel: UnwrapRef<typeof import('@vueuse/core')['useVModel']>;
    readonly useVModels: UnwrapRef<typeof import('@vueuse/core')['useVModels']>;
    readonly useVibrate: UnwrapRef<typeof import('@vueuse/core')['useVibrate']>;
    readonly useVirtualList: UnwrapRef<typeof import('@vueuse/core')['useVirtualList']>;
    readonly useWakeLock: UnwrapRef<typeof import('@vueuse/core')['useWakeLock']>;
    readonly useWebNotification: UnwrapRef<typeof import('@vueuse/core')['useWebNotification']>;
    readonly useWebSocket: UnwrapRef<typeof import('@vueuse/core')['useWebSocket']>;
    readonly useWebWorker: UnwrapRef<typeof import('@vueuse/core')['useWebWorker']>;
    readonly useWebWorkerFn: UnwrapRef<typeof import('@vueuse/core')['useWebWorkerFn']>;
    readonly useWindowFocus: UnwrapRef<typeof import('@vueuse/core')['useWindowFocus']>;
    readonly useWindowScroll: UnwrapRef<typeof import('@vueuse/core')['useWindowScroll']>;
    readonly useWindowSize: UnwrapRef<typeof import('@vueuse/core')['useWindowSize']>;
    readonly watch: UnwrapRef<typeof import('vue')['watch']>;
    readonly watchArray: UnwrapRef<typeof import('@vueuse/core')['watchArray']>;
    readonly watchAtMost: UnwrapRef<typeof import('@vueuse/core')['watchAtMost']>;
    readonly watchDebounced: UnwrapRef<typeof import('@vueuse/core')['watchDebounced']>;
    readonly watchDeep: UnwrapRef<typeof import('@vueuse/core')['watchDeep']>;
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>;
    readonly watchIgnorable: UnwrapRef<typeof import('@vueuse/core')['watchIgnorable']>;
    readonly watchImmediate: UnwrapRef<typeof import('@vueuse/core')['watchImmediate']>;
    readonly watchOnce: UnwrapRef<typeof import('@vueuse/core')['watchOnce']>;
    readonly watchPausable: UnwrapRef<typeof import('@vueuse/core')['watchPausable']>;
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>;
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>;
    readonly watchThrottled: UnwrapRef<typeof import('@vueuse/core')['watchThrottled']>;
    readonly watchTriggerable: UnwrapRef<typeof import('@vueuse/core')['watchTriggerable']>;
    readonly watchWithFilter: UnwrapRef<typeof import('@vueuse/core')['watchWithFilter']>;
    readonly whenever: UnwrapRef<typeof import('@vueuse/core')['whenever']>;
  }
}
