/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'auth-register': RouteRecordInfo<'auth-register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/budget-stats': RouteRecordInfo<'/budget-stats', '/budget-stats', Record<never, never>, Record<never, never>>,
    '/color-selector-test': RouteRecordInfo<'/color-selector-test', '/color-selector-test', Record<never, never>, Record<never, never>>,
    '/datetime-test': RouteRecordInfo<'/datetime-test', '/datetime-test', Record<never, never>, Record<never, never>>,
    'family-ledger': RouteRecordInfo<'family-ledger', '/family-ledger', Record<never, never>, Record<never, never>, 'family-ledger-detail'>,
    'family-ledger-detail': RouteRecordInfo<'family-ledger-detail', '/family-ledger/:serialNum', { serialNum: ParamValue<true> }, { serialNum: ParamValue<false> }>,
    'health-period': RouteRecordInfo<'health-period', '/health/period', Record<never, never>, Record<never, never>>,
    'money': RouteRecordInfo<'money', '/money', Record<never, never>, Record<never, never>>,
    'projects': RouteRecordInfo<'projects', '/projects', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'splashscreen': RouteRecordInfo<'splashscreen', '/splash', Record<never, never>, Record<never, never>>,
    'tags': RouteRecordInfo<'tags', '/tags', Record<never, never>, Record<never, never>>,
    'theme-demo': RouteRecordInfo<'theme-demo', '/theme-demo', Record<never, never>, Record<never, never>>,
    'todos': RouteRecordInfo<'todos', '/todos', Record<never, never>, Record<never, never>>,
    'transaction-stats': RouteRecordInfo<'transaction-stats', '/transaction-stats', Record<never, never>, Record<never, never>>,
  }
}
